"""Pure logic for churn-artifact merge reconciliation (no git / no IO).

Split out of ``tools/resolve_churn_conflicts.py`` so the allowlist + the
classify / dedup / validate rules are unit-testable in isolation and the tool
stays under the 300-LOC source guideline. See
``.shipwright/planning/iterate/2026-05-31-churn-merge-resolver.md``.
"""

from __future__ import annotations

import fnmatch
import json

# Triage-log validation lives in lib.triage_validate and the triage dedup in
# lib.triage_dedup (both extracted so this module stays under the 300-LOC
# guideline). Re-exported so the historical
# `from lib.churn_merge import validate_triage_text` / `dedup_triage_lines`
# import paths are unchanged.
from lib.jsonl_records import split_records
from lib.triage_dedup import dedup_triage_lines  # noqa: F401  (re-export: see lib/triage_dedup.py)
from lib.triage_validate import (  # noqa: F401  (re-export surface)
    TriageValidation,
    classify_triage_text,
    validate_triage_text,
)

# --- the churn allowlist (POSIX relpaths) -----------------------------------

COMPLIANCE_MDS: frozenset[str] = frozenset(
    f".shipwright/compliance/{name}.md"
    for name in ("dashboard", "sbom", "test-evidence", "traceability-matrix", "change-history")
)
AGENT_DOC_MDS: frozenset[str] = frozenset(
    f".shipwright/agent_docs/{name}.md"
    for name in ("build_dashboard", "session_handoff", "triage_inbox")
)
DERIVED_MDS: frozenset[str] = COMPLIANCE_MDS | AGENT_DOC_MDS

EVENTS_LOG = "shipwright_events.jsonl"
TEST_RESULTS = "shipwright_test_results.json"
#: The triage backlog — an append-only JSONL log tracked since campaign
#: 2026-06-05-track-triage-jsonl (C). Reconciled like ``EVENTS_LOG`` but with a
#: triage-specific dedup whose id-collision rule differs from the events one —
#: see :mod:`lib.triage_dedup`.
TRIAGE_LOG = ".shipwright/triage.jsonl"

#: The committed CI-security scan summary — a DERIVED compliance snapshot like the
#: five compliance MDs (regenerated by the SAME ``_update_compliance`` producer,
#: which iterdir-covers the whole ``.shipwright/compliance/`` dir), but a ``.json``
#: (the WebUI dashboard reads it as structured data), so the ``.md``-shaped
#: :data:`DERIVED_MDS` missed it. Kept as its OWN constant (NOT folded into
#: ``DERIVED_MDS``, whose name is ``.md``-specific) so the exact-path doc-sync
#: registry test stays a 1:1 mapping. Resolved like a DERIVED_MD: ``--theirs``
#: (mainline) placeholder at conflict, then a best-effort regenerate in the
#: follow-up (``refresh_ci_security`` is fail-soft — the placeholder stands when
#: there is no fresh ``security.yml`` run).
CI_SECURITY_SUMMARY = ".shipwright/compliance/ci-security.json"

#: The committed requirement→test traceability snapshot — the ``test_links``
#: collector output, a DERIVED compliance snapshot regenerated by the SAME
#: ``_update_compliance --phase iterate`` producer as the compliance MDs, but a
#: ``.json`` (the layer-aware RTM reads it as structured data), so the
#: ``.md``-shaped :data:`DERIVED_MDS` missed it. Its own constant like
#: :data:`CI_SECURITY_SUMMARY` (NOT folded into ``DERIVED_MDS``, whose name is
#: ``.md``-specific) so the doc-sync registry test stays a 1:1 mapping. Resolved
#: like a DERIVED_MD: ``--theirs`` placeholder at conflict, then re-derived +
#: staged in the follow-up. (Was the CHURN_ALLOWLIST gap that forced a manual
#: ``--theirs`` in iterate #391.)
TEST_TRACEABILITY = ".shipwright/compliance/test-traceability.json"

#: The ADR spec folder's generated index — the one entry an iterate BRANCH
#: legitimately carries, which is what created this conflict class. Resolved like
#: a DERIVED_MD (``--theirs``, then re-derive). Why: ADR-118 + the doc table row.
ADR_INDEX = ".shipwright/planning/adr/INDEX.md"

#: ``decision_log.md``'s generated index — same treatment as :data:`ADR_INDEX`
#: and for the same reason: ``write_decision_log.py`` (plan/build/deploy) and
#: ``aggregate_decisions.py`` (release) each refresh it as a pure function of
#: ``decision_log.md``'s own content, so a merge conflict on it is always
#: correctly resolved by re-deriving from the MERGED file rather than picking
#: a side. NOT a :data:`DERIVED_MDS` member for the same reason ADR_INDEX
#: isn't: that register is for views that are *wrong* when derived on a
#: branch, and this one is correct on a branch by construction. The sibling
#: decision-drops index is deliberately absent — see
#: ``lib/decision_drops_index.py``: that directory is gitignored, so git can
#: never see a conflict on it and an allowlist entry would be exercised by
#: nothing.
DECISION_LOG_INDEX = ".shipwright/agent_docs/decision_log_index.md"

#: Derived iterate-throughput report, regenerated every F5b run — own constant like :data:`CI_SECURITY_SUMMARY`.
THROUGHPUT_REPORT = ".shipwright/compliance/performance/iterate-throughput.md"

#: Everything the resolver may auto-resolve. A conflict outside this set aborts.
#: NOTE: ``.shipwright/agent_docs/architecture.md`` is intentionally absent
#: (curated prose — must reach a human; folds external-review G4/O1).
CHURN_ALLOWLIST: frozenset[str] = DERIVED_MDS | {
    EVENTS_LOG, TEST_RESULTS, TRIAGE_LOG, CI_SECURITY_SUMMARY, TEST_TRACEABILITY,
    ADR_INDEX, DECISION_LOG_INDEX, THROUGHPUT_REPORT,
}

#: Per-campaign status boards (campaign 2026-06-07-tracked-campaign-status, S3)
#: are tracked per-tree churn artifacts but live at a WILDCARD path — one
#: ``status.json`` per campaign slug — so they cannot be fixed
#: :data:`CHURN_ALLOWLIST` entries. They are admitted by the
#: :func:`is_campaign_status` glob predicate instead and resolved like a
#: DERIVED_MD (placeholder side at conflict, then regenerate-from-events in the
#: follow-up). Kept OUT of ``CHURN_ALLOWLIST`` so the exact-path doc-sync
#: registry test (``test_churn_merge_doc_sync``) stays a 1:1 mapping.
CAMPAIGN_STATUS_GLOB = ".shipwright/planning/iterate/campaigns/*/status.json"


def norm(rel: str) -> str:
    """Normalise a git path to forward-slash POSIX form."""
    return rel.strip().replace("\\", "/")


def is_campaign_status(rel: str) -> bool:
    """True iff ``rel`` is a campaign ``status.json`` (glob-matched, one slug).

    Matches :data:`CAMPAIGN_STATUS_GLOB`. ``fnmatch``'s ``*`` would span ``/``,
    so a path-segment count guard pins the single ``*`` to exactly one segment
    (the campaign slug): ``campaigns/a/b/status.json`` does NOT match. Normalises
    backslashes so the predicate is robust when called standalone (``classify``
    already feeds it normalised paths).
    """
    rel = norm(rel)
    # fnmatchcase (NOT fnmatch): git paths are case-sensitive POSIX, but fnmatch
    # applies os.path.normcase → case-INSENSITIVE on Windows, a platform-divergent
    # gate. The segment-count guard pins the single ``*`` to one slug segment.
    return (
        fnmatch.fnmatchcase(rel, CAMPAIGN_STATUS_GLOB)
        and rel.count("/") == CAMPAIGN_STATUS_GLOB.count("/")
    )


def is_derived_churn(rel: str) -> bool:
    """True iff ``rel`` is a REGENERATED artifact rather than authored content.

    The single definition of "derived", for every consumer that needs one.
    :func:`classify` asks it to decide what the merge resolver may auto-resolve;
    the F11 ``no silent revert`` check asks it to decide which paths are exempt
    from line-level comparison, because a regenerated file legitimately changes
    wholesale on every integration.

    Those two used to hold *different* answers: the verifier asked
    ``path in CHURN_ALLOWLIST`` while ``classify`` asked
    ``... or is_campaign_status(rel)``, so a campaign ``status.json`` was
    regenerated churn to the resolver and authored content to the verifier
    (found by the review cascade during #488, deferred there). One predicate,
    called by both, is what makes that drift unrepresentable.

    Pure and dependency-light on purpose (stdlib only, one normalised
    repo-relative path in): the verifier package imports this module, so
    anything heavier here would couple the merge resolver to verifier concerns
    (external plan review, openai #8).
    """
    rel = norm(rel)
    return rel in CHURN_ALLOWLIST or is_campaign_status(rel)


def classify(conflicted: object) -> tuple[list[str], list[str]]:
    """Split conflicted paths into ``(resolvable, blocking)``.

    ``resolvable`` = whatever :func:`is_derived_churn` admits —
    :data:`CHURN_ALLOWLIST` members ∪ campaign ``status.json`` files;
    ``blocking`` is everything else (real source / curated prose). Both lists are
    normalised + de-duplicated + sorted. The pre-flight gate aborts whenever
    ``blocking`` is non-empty (AC-3).
    """
    resolvable: list[str] = []
    blocking: list[str] = []
    for raw in conflicted:  # type: ignore[union-attr]
        rel = norm(str(raw))
        if not rel:
            continue
        (resolvable if is_derived_churn(rel) else blocking).append(rel)
    return sorted(set(resolvable)), sorted(set(blocking))


def dedup_event_lines(lines: list[str]) -> tuple[list[str], list[str]]:
    """Exact-line dedup preserving first-seen order (never drops a *distinct*
    line). Returns ``(deduped, warnings)``; a warning is emitted — never a drop —
    when two *distinct* lines share an ``evt`` ``id`` (32-bit ids can collide;
    folds external-review G2/O6).

    The ``id`` extraction below is total: never raises. A deeply-nested value
    makes ``json.loads`` raise ``RecursionError`` — the sibling of the defect
    fixed in ``lib.triage_dedup._parsed_append`` for the same reason (card
    trg-57d0d6d3 / P2.19g, TEIL 2; found here by the internal Opus plan
    review, not by the originating card, which named only the triage-log call
    site). A line whose id cannot be extracted degrades to ``ev_id = None``
    and is neither dropped nor mutated — it is simply invisible to the
    id-collision warning below, exactly as an unparseable line already was.

    ``isinstance`` FIRST, same load-bearing order as ``sweep_quarantine.py``'s
    orphan-id check: an id may be any JSON value, and ``[] in {}`` raises
    ``TypeError: unhashable type`` — testing membership first would crash this
    function from inside the same canonical-lock caller the RecursionError
    guard exists to protect (doubt-reviewer finding, Stage 3, this run).
    """
    seen_lines: set[str] = set()
    id_to_line: dict[str, str] = {}
    out: list[str] = []
    warnings: list[str] = []
    for line in lines:
        if not line.strip():
            continue
        if line in seen_lines:
            continue
        seen_lines.add(line)
        out.append(line)
        try:
            ev_id = json.loads(line).get("id")
        except (AttributeError, ValueError, RecursionError):
            ev_id = None
        if isinstance(ev_id, str) and ev_id:
            if ev_id in id_to_line and id_to_line[ev_id] != line:
                warnings.append(
                    f"evt id {ev_id!r} shared by two DISTINCT event lines "
                    "(kept both — verify no real duplication)"
                )
            id_to_line.setdefault(ev_id, line)
    return out, warnings


# `TriageValidation`, `classify_triage_text`, and `validate_triage_text` now live in
# lib.triage_validate; `dedup_triage_lines` lives in lib.triage_dedup (both
# re-exported at the top of this module, both extracted to keep this file under the
# 300-LOC guideline). See those modules for the triage-log validation +
# orphan-status rules and for the same-id append collision rule respectively.


def validate_events_text(text: str, *, require_run_id: str | None = None) -> list[str]:
    """Return a list of error strings (empty = valid).

    Checks: (a) every non-blank line decodes as a sequence of one or more JSON
    OBJECTS (records) — a merge=union concatenation of valid records is recovered
    and is NOT an error; only an unrecoverable remainder (or a non-object line) is
    reported; (b) if ``require_run_id`` is given, a ``work_completed`` event whose
    ``adr_id`` == that run id exists (so F11 ``check_events_has_commit`` stays
    green). Folds G5/O4/O5.
    """
    errors: list[str] = []
    run_id_seen = False
    for n, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            continue
        # Record-boundary recovery via the shared SSoT: AC7 of
        # iterate-2026-07-19-…-readers pins that a merge=union merge can leave two
        # records on one physical line and propagate it into main. The pre-fix
        # per-line json.loads reported such a line as "not valid JSON" AND missed a
        # require_run_id match sitting on it — a FALSE check_events_has_commit
        # failure during integrate_main (fixed here,
        # iterate-2026-07-20-events-record-boundary-remainder). A fully-recoverable
        # concatenation is a union artefact, not corruption; only an unrecoverable
        # remainder is still reported (check (a) preserved).
        records, remainder = split_records(stripped)
        for obj in records:
            if (
                require_run_id
                and obj.get("type") == "work_completed"
                and obj.get("adr_id") == require_run_id
            ):
                run_id_seen = True
        if remainder:
            errors.append(
                f"line {n}: not valid JSON (unrecoverable fragment) — union may have corrupted a historic line"
            )
    if require_run_id and not run_id_seen:
        errors.append(
            f"this run's work_completed event (adr_id={require_run_id}) is absent — "
            "the merge dropped it; F11 would fail"
        )
    return errors
