#!/usr/bin/env python3
"""Generated gitleaks configuration for the local secret scan.

Gitleaks has no ``--exclude`` flag and ignores ``.gitignore`` in detect-mode, so
the plugin has always handed it a generated TOML carrying the shipwright path
exclusions as an ``[allowlist] paths`` array. That generated file was passed as
``--config``, which **replaces** whatever the repository ships — including its
own ``.gitleaks.toml``.

That was a divergence: the adopt-scaffolded ``security.yml`` runs
``gitleaks detect --no-git`` with NO ``--config``, so gitleaks auto-loads
``.gitleaks.toml`` from the repository root. The same repository therefore
produced different results depending on which path asked — the host honoured
the project's accepted findings, the local scan did not.

Now the generated config **extends** the project's file when one exists:

    [extend]
    path = "<abs path to the project's .gitleaks.toml>"

so a repository has one accepted-findings answer. Two consequences are load-bearing:

1. **Never emit both ``useDefault`` and ``path``.** Gitleaks aborts on a config
   that sets both, which would break every local secret scan. Exactly one is
   rendered — pinned by a test.
2. **The plugin's own placeholder allowlist is dropped in extend-mode.** With a
   project file present, that file is the repository's answer; keeping an extra
   plugin-side allowlist would leave the local scan quietly MORE permissive
   than the host, which is the divergence this module removes. With no project
   file there is no answer to defer to, so the previous generated config —
   ``useDefault`` plus the ``cafebabe:deadbeef`` placeholder defence — is
   unchanged.
"""

from __future__ import annotations

import os
import re
import tempfile

from gitleaks_inspect import (  # noqa: F401  (PROJECT_CONFIG_NAME re-exported)
    PROJECT_CONFIG_NAME,
    chains_to_another_file,
    resolve_project_config,
)

_HEADER = "# Auto-generated by shipwright-security — do not edit manually.\n"

# Defense-in-depth for the no-project-config case: the famous magic-hex
# placeholder cafebabe:deadbeef false-matches the built-in sidekiq-secret rule
# but is never a real secret. Mirrors
# shared/templates/github-actions/gitleaks.toml.template.
_PLACEHOLDER_ALLOWLIST = (
    '# magic-hex placeholder (cafebabe:deadbeef) — false sidekiq-secret match\n'
    'regexTarget = "match"\n'
    "regexes = ['''cafebabe:deadbeef''']\n"
    'stopwords = ["cafebabe", "deadbeef"]\n'
)




_TOML_ESCAPES = {
    "\\": "\\\\",
    '"': '\\"',
    "\b": "\\b",
    "\t": "\\t",
    "\n": "\\n",
    "\f": "\\f",
    "\r": "\\r",
}


def _toml_basic_string(value: str) -> str:
    r"""Quote ``value`` as a TOML basic string.

    Full escaping, not just backslash + quote. A Windows path is full of
    backslashes, and every other control character is an escape sequence inside
    a basic string too — a partially-escaped path either fails to parse or
    silently points somewhere else, and "somewhere else" for a scanner config
    means scanning under rules nobody chose. Anything below U+0020 (and U+007F)
    that has no short form goes out as ``\uXXXX``.
    """
    out = []
    for ch in value:
        if ch in _TOML_ESCAPES:
            out.append(_TOML_ESCAPES[ch])
        elif ch < " " or ch == "":
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'




def render_config(
    excludes: tuple[str, ...], project_config_path: str | None = None
) -> str:
    """Render the generated gitleaks TOML.

    Args:
        excludes: folder names to allowlist as path segments. Callers pass
            names already validated against ``oss_backend._SIMPLE_NAME_RE``, so
            interpolation here is safe; ``re.escape`` anchors them to a segment
            boundary rather than a substring.
        project_config_path: absolute path to the repository's own
            ``.gitleaks.toml``. When given, it is extended; when ``None``, the
            gitleaks built-in ruleset is used directly.
    """
    # TOML single-quote literal strings: no escape processing, so the regex
    # backslashes pass through verbatim.
    patterns = [f"'(^|/){re.escape(name)}(/|$)'" for name in excludes]

    if project_config_path:
        extend_block = (
            "[extend]\n"
            f"path = {_toml_basic_string(project_config_path)}\n"
        )
        # The project's file is the repository's accepted-findings answer; the
        # only thing we add is the path exclusions gitleaks cannot derive.
        allowlist_extra = ""
        provenance = (
            f"# Extends the project's {PROJECT_CONFIG_NAME} so the local scan and the\n"
            "# host workflow honour the same accepted findings.\n"
        )
    else:
        extend_block = "[extend]\nuseDefault = true\n"
        allowlist_extra = _PLACEHOLDER_ALLOWLIST
        provenance = (
            f"# No {PROJECT_CONFIG_NAME} at the scanned root — using the gitleaks\n"
            "# built-in ruleset plus the shipwright default exclusions.\n"
        )

    return (
        _HEADER
        + provenance
        + 'title = "shipwright allowlist"\n'
        + "\n"
        + extend_block
        + "\n"
        + "[allowlist]\n"
        + 'description = "shipwright default scanner exclusions"\n'
        + f"paths = [{', '.join(patterns)}]\n"
        + allowlist_extra
    )


def write_config(
    excludes: tuple[str, ...], project_config_path: str | None = None
) -> str:
    """Write :func:`render_config` to a temp file and return its path.

    The caller owns cleanup (``oss_backend._run_gitleaks`` unlinks it in a
    ``finally``).
    """
    fd, path = tempfile.mkstemp(suffix=".toml", prefix="shipwright-gitleaks-")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(render_config(excludes, project_config_path))
    return path


def config_for_scan(target: str, excludes: tuple[str, ...]) -> tuple[str, bool]:
    """The ``--config`` to hand gitleaks for ``target``, and whether we own it.

    Three cases, in order of how much we may add:

    - **No project config** — render ours (``useDefault`` + the exclusions).
    - **A project config we can wrap** — render ours extending it, so the
      repository's accepted findings AND the shipwright exclusions both apply.
    - **A project config that already extends a second file** — hand gitleaks
      the project's file UNCHANGED and forgo the exclusions.

    The third case is not a preference. Wrapping a chain leaves the built-in
    rules unreachable, and a scan that finds nothing because its rules went
    missing is worse than a noisy one: parity is the guarantee AC-1 makes, the
    exclusions are a convenience. See :func:`gitleaks_inspect.chains_to_another_file`
    for the measurement.

    Returns ``(path, owned)``. ``owned`` is False for the project's own file —
    the caller must not unlink it.
    """
    project = resolve_project_config(target)
    if project is not None and chains_to_another_file(target):
        return project, False
    return write_config(excludes, project), True
