#!/usr/bin/env python3
"""Generated gitleaks configuration for the local secret scan.

Gitleaks has no ``--exclude`` flag and ignores ``.gitignore`` in detect-mode, so
the plugin has always handed it a generated TOML carrying the shipwright path
exclusions as an ``[allowlist] paths`` array. That generated file was passed as
``--config``, which **replaces** whatever the repository ships — including its
own ``.gitleaks.toml``.

That was a divergence: the adopt-scaffolded ``security.yml`` runs
``gitleaks detect --no-git`` with NO ``--config``, so gitleaks auto-loads
``.gitleaks.toml`` from the repository root. The same repository therefore
produced different results depending on which path asked — the host honoured
the project's accepted findings, the local scan did not.

Now the generated config **extends** the project's file when one exists:

    [extend]
    path = "<abs path to the project's .gitleaks.toml>"

so a repository has one accepted-findings answer. Two consequences are load-bearing:

1. **Never emit both ``useDefault`` and ``path``.** Gitleaks aborts on a config
   that sets both, which would break every local secret scan. Exactly one is
   rendered — pinned by a test.
2. **The plugin's own placeholder allowlist is dropped in extend-mode.** With a
   project file present, that file is the repository's answer; keeping an extra
   plugin-side allowlist would leave the local scan quietly MORE permissive
   than the host, which is the divergence this module removes. With no project
   file there is no answer to defer to, so the previous generated config —
   ``useDefault`` plus the ``cafebabe:deadbeef`` placeholder defence — is
   unchanged.
"""

from __future__ import annotations

import os
import re
import tempfile
import tomllib

# Gitleaks auto-loads this filename from the scan source directory when no
# ``--config`` is given; it is what the host path reads, so it is the file the
# local path must extend.
PROJECT_CONFIG_NAME = ".gitleaks.toml"

_HEADER = "# Auto-generated by shipwright-security — do not edit manually.\n"

# Defense-in-depth for the no-project-config case: the famous magic-hex
# placeholder cafebabe:deadbeef false-matches the built-in sidekiq-secret rule
# but is never a real secret. Mirrors
# shared/templates/github-actions/gitleaks.toml.template.
_PLACEHOLDER_ALLOWLIST = (
    '# magic-hex placeholder (cafebabe:deadbeef) — false sidekiq-secret match\n'
    'regexTarget = "match"\n'
    "regexes = ['''cafebabe:deadbeef''']\n"
    'stopwords = ["cafebabe", "deadbeef"]\n'
)


def resolve_project_config(target: str) -> str | None:
    """Absolute path to the project's ``.gitleaks.toml`` at ``target``, if any.

    Keyed to the SCANNED target root rather than the process working directory
    — same contract as ``oss_backend._resolve_trivy_ignorefile``, because the
    CWD differs between CI and a local run while the scanned root does not.

    **Absolute, always.** Gitleaks resolves ``[extend] path`` against its own
    working directory, so a relative path here would point somewhere else — or
    nowhere — the moment the scan is launched from a different directory than
    the target. ``abspath`` is what makes the extend safe to emit.
    """
    candidate = os.path.abspath(os.path.join(target, PROJECT_CONFIG_NAME))
    return candidate if os.path.isfile(candidate) else None


_TOML_ESCAPES = {
    "\\": "\\\\",
    '"': '\\"',
    "\b": "\\b",
    "\t": "\\t",
    "\n": "\\n",
    "\f": "\\f",
    "\r": "\\r",
}


def _toml_basic_string(value: str) -> str:
    r"""Quote ``value`` as a TOML basic string.

    Full escaping, not just backslash + quote. A Windows path is full of
    backslashes, and every other control character is an escape sequence inside
    a basic string too — a partially-escaped path either fails to parse or
    silently points somewhere else, and "somewhere else" for a scanner config
    means scanning under rules nobody chose. Anything below U+0020 (and U+007F)
    that has no short form goes out as ``\uXXXX``.
    """
    out = []
    for ch in value:
        if ch in _TOML_ESCAPES:
            out.append(_TOML_ESCAPES[ch])
        elif ch < " " or ch == "":
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def inspect_project_config(path: str) -> dict[str, bool]:
    """Report what a project ``.gitleaks.toml`` brings to the rule set.

    Returns ``{"parsed", "extends_default", "extends_other", "defines_rules"}``.

    This exists because of a real hazard in extend-mode. Gitleaks aborts when a
    config sets both ``extend.useDefault`` and ``extend.path``, so extending the
    project's file means the plugin can no longer force the built-in ruleset on:
    responsibility for it moves to that file. A project file authored purely to
    hold an ``[allowlist]``, with no ``[extend] useDefault = true`` and no rules
    of its own, therefore scans with almost NO secret rules.

    The host workflow already behaves that way (it loads the same file with no
    ``--config``), so this is not a new divergence — it is a pre-existing hole
    that extending makes visible. Naming it is the entire point of this
    plugin's coverage manifest: a class scanned with no rules is unexamined,
    not clean. An unparseable file returns ``parsed: False`` and is reported
    the same conservative way.
    """
    result = {
        "parsed": False,
        "extends_default": False,
        "extends_other": False,
        "defines_rules": False,
    }
    try:
        with open(path, "rb") as fh:
            data = tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError, ValueError):
        return result
    if not isinstance(data, dict):
        return result
    result["parsed"] = True
    extend = data.get("extend")
    if isinstance(extend, dict):
        result["extends_default"] = bool(extend.get("useDefault"))
        result["extends_other"] = bool(extend.get("path") or extend.get("url"))
    rules = data.get("rules")
    result["defines_rules"] = isinstance(rules, list) and len(rules) > 0
    return result


def _brings_rules(path: str, _depth: int = 0) -> bool | None:
    """Does the config at ``path`` end up with an effective ruleset?

    ``True`` yes, ``False`` no, ``None`` cannot tell. Follows a LOCAL
    ``extend.path`` one hop — gitleaks' own ``maxExtendDepth`` is 2, so a deeper
    chain is not honoured by the scanner either — and refuses to guess about an
    ``extend.url``, which cannot be inspected offline.
    """
    info = inspect_project_config(path)
    if not info["parsed"]:
        return None
    if info["extends_default"] or info["defines_rules"]:
        return True
    if info["extends_other"]:
        if _depth >= 1:
            return None  # deeper than gitleaks itself follows
        chained = _chained_path(path)
        if chained is None:
            return None  # a URL, or an unresolvable path
        return _brings_rules(chained, _depth + 1)
    return False


def _chained_path(path: str) -> str | None:
    """Absolute local path this config extends, or ``None`` for a URL/absent."""
    try:
        with open(path, "rb") as fh:
            data = tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError, ValueError):
        return None
    extend = data.get("extend") if isinstance(data, dict) else None
    if not isinstance(extend, dict) or extend.get("url"):
        return None
    target = extend.get("path")
    if not isinstance(target, str) or not target:
        return None
    resolved = target if os.path.isabs(target) else os.path.join(
        os.path.dirname(path), target)
    return resolved if os.path.isfile(resolved) else None


def project_config_warning(target: str) -> str | None:
    """Human-readable warning when the project's gitleaks config would leave the
    secret scan with (next to) no rules — otherwise ``None``.

    Callers annotate the ``secrets`` coverage row with this, so a scan running
    against an empty ruleset says so instead of reporting a clean class.
    """
    path = resolve_project_config(target)
    if path is None:
        return None
    info = inspect_project_config(path)
    if not info["parsed"]:
        return (
            f"{PROJECT_CONFIG_NAME} could not be parsed; the secret scan is "
            "running under whatever gitleaks makes of it"
        )
    brings_rules = _brings_rules(path)
    if brings_rules is None:
        # An un-inspectable extension (a URL, or a chain deeper than gitleaks
        # follows). Claiming clean here would be the false-clean this card
        # exists to remove, so it is reported as unverifiable.
        return (
            f"{PROJECT_CONFIG_NAME} extends a source that cannot be inspected "
            "offline, so whether the secret scan had an effective ruleset is "
            "unverifiable"
        )
    if brings_rules:
        return None
    return (
        f"{PROJECT_CONFIG_NAME} sets no rules and does not extend the gitleaks "
        "defaults ([extend] useDefault = true), so this scan looked for almost "
        "nothing — the same ruleset the host workflow uses for this repo"
    )


def class_degradations(target: str) -> dict[str, str]:
    """``{"secrets": <reason>}`` for ``scan_coverage.build_coverage``, or ``{}``.

    A DEGRADATION, not a footnote. The secret scan ran, but under a ruleset known
    to be ineffective, so its result cannot be trusted — and a class whose result
    cannot be trusted must not be reported `covered`. Annotating a `covered` row
    with a caveat was the bug: `is_complete()` stayed true, the report showed no
    banner, and the card said "every class was checked" while the detail beside
    it said the scan looked for almost nothing.

    One call site per scan entry point, so the signal cannot be wired into one
    report and forgotten in the other.
    """
    reason = project_config_warning(target)
    return {"secrets": reason} if reason else {}


def render_config(
    excludes: tuple[str, ...], project_config_path: str | None = None
) -> str:
    """Render the generated gitleaks TOML.

    Args:
        excludes: folder names to allowlist as path segments. Callers pass
            names already validated against ``oss_backend._SIMPLE_NAME_RE``, so
            interpolation here is safe; ``re.escape`` anchors them to a segment
            boundary rather than a substring.
        project_config_path: absolute path to the repository's own
            ``.gitleaks.toml``. When given, it is extended; when ``None``, the
            gitleaks built-in ruleset is used directly.
    """
    # TOML single-quote literal strings: no escape processing, so the regex
    # backslashes pass through verbatim.
    patterns = [f"'(^|/){re.escape(name)}(/|$)'" for name in excludes]

    if project_config_path:
        extend_block = (
            "[extend]\n"
            f"path = {_toml_basic_string(project_config_path)}\n"
        )
        # The project's file is the repository's accepted-findings answer; the
        # only thing we add is the path exclusions gitleaks cannot derive.
        allowlist_extra = ""
        provenance = (
            f"# Extends the project's {PROJECT_CONFIG_NAME} so the local scan and the\n"
            "# host workflow honour the same accepted findings.\n"
        )
    else:
        extend_block = "[extend]\nuseDefault = true\n"
        allowlist_extra = _PLACEHOLDER_ALLOWLIST
        provenance = (
            f"# No {PROJECT_CONFIG_NAME} at the scanned root — using the gitleaks\n"
            "# built-in ruleset plus the shipwright default exclusions.\n"
        )

    return (
        _HEADER
        + provenance
        + 'title = "shipwright allowlist"\n'
        + "\n"
        + extend_block
        + "\n"
        + "[allowlist]\n"
        + 'description = "shipwright default scanner exclusions"\n'
        + f"paths = [{', '.join(patterns)}]\n"
        + allowlist_extra
    )


def write_config(
    excludes: tuple[str, ...], project_config_path: str | None = None
) -> str:
    """Write :func:`render_config` to a temp file and return its path.

    The caller owns cleanup (``oss_backend._run_gitleaks`` unlinks it in a
    ``finally``).
    """
    fd, path = tempfile.mkstemp(suffix=".toml", prefix="shipwright-gitleaks-")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(render_config(excludes, project_config_path))
    return path
