"""Tests for Group E staleness detection (plan v7, Step 2)."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

# Add plugin root so ``scripts.audit`` + ``scripts.lib`` both import cleanly.
PLUGIN_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PLUGIN_ROOT))

from scripts.audit.audit_staleness import (  # noqa: E402
    DOC_REGISTRY,
    HEADER_STRIP_RE,
    check_staleness,
    compare_doc,
    normalize,
)


# ---------------------------------------------------------------------------
# Pure-function tests — no generator dependency
# ---------------------------------------------------------------------------


def test_header_strip_removes_generated_line():
    text = "Title\nGenerated: 2026-04-19T12:00:00Z\nBody\n"
    assert normalize(text) == "Title\nBody\n"


def test_header_strip_preserves_other_lines():
    text = "# RTM\n\nGenerated: 2026-04-19\n## Summary\nGenerated: ignore-me\n"
    # Both "Generated:" lines stripped; rest preserved verbatim.
    assert normalize(text) == "# RTM\n\n## Summary\n"


def test_header_strip_idempotent():
    text = "Generated: x\nfoo\nGenerated: y\nbar\n"
    once = normalize(text)
    twice = normalize(once)
    assert once == twice == "foo\nbar\n"


def test_header_strip_ignores_substring_matches():
    # Lines that mention "Generated:" mid-line must NOT be stripped.
    text = "Section: Generated by pipeline (note)\nbody\n"
    assert normalize(text) == text


def test_header_strip_re_is_multiline():
    # Sanity check on the exported regex itself.
    assert HEADER_STRIP_RE.flags & 8  # re.MULTILINE


# ---------------------------------------------------------------------------
# compare_doc with synthetic generator output
# ---------------------------------------------------------------------------


class _FakeDoc:
    def __init__(self, key, rel_path):
        self.key = key
        self.rel_path = rel_path


def test_compare_doc_missing_file_flagged_stale(tmp_path):
    doc = _FakeDoc("rtm", "compliance/traceability-matrix.md")
    # Intentionally do NOT create the file.
    result = compare_doc(tmp_path, doc, "Generated: now\n# RTM\nBody\n")
    assert result.exists is False
    assert result.stale is True


def test_compare_doc_fresh_match_after_header_strip(tmp_path):
    doc = _FakeDoc("rtm", "compliance/traceability-matrix.md")
    path = tmp_path / doc.rel_path
    path.parent.mkdir(parents=True)
    path.write_text("Generated: 2024-01-01\n# RTM\nBody\n", encoding="utf-8")

    # Generator output with a different timestamp but otherwise identical.
    fresh = "Generated: 2026-04-19\n# RTM\nBody\n"
    result = compare_doc(tmp_path, doc, fresh)
    assert result.exists is True
    assert result.stale is False
    assert result.first_diff_line is None


def test_compare_doc_detects_real_body_drift(tmp_path):
    doc = _FakeDoc("rtm", "compliance/traceability-matrix.md")
    path = tmp_path / doc.rel_path
    path.parent.mkdir(parents=True)
    path.write_text("Generated: 2024-01-01\n# RTM\nOld body\n", encoding="utf-8")

    fresh = "Generated: 2026-04-19\n# RTM\nNew body\n"
    result = compare_doc(tmp_path, doc, fresh)
    assert result.stale is True
    # First differing line post-normalization: "# RTM" matches, then line 2 drifts.
    assert result.first_diff_line == 2


def test_compare_doc_reports_line_delta_on_added_rows(tmp_path):
    doc = _FakeDoc("rtm", "compliance/traceability-matrix.md")
    path = tmp_path / doc.rel_path
    path.parent.mkdir(parents=True)
    path.write_text("Generated: x\nline A\n", encoding="utf-8")
    fresh = "Generated: x\nline A\nline B\nline C\n"

    result = compare_doc(tmp_path, doc, fresh)
    assert result.stale is True
    assert result.line_delta == 2


# ---------------------------------------------------------------------------
# check_staleness end-to-end with stub renderers
# ---------------------------------------------------------------------------


def _make_renderers(stub_text_by_key):
    """Return a renderer dict driven by a static map (key -> str)."""
    def _renderer_for(key):
        def _fn(_data):
            return stub_text_by_key[key]
        return _fn
    return {k: _renderer_for(k) for k in stub_text_by_key}


def _write_doc(project_root, rel_path, text):
    path = project_root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def test_check_staleness_all_fresh(tmp_path):
    # Every renderer matches its on-disk file after header strip.
    fresh_docs = {}
    for doc in DOC_REGISTRY:
        content = f"Generated: now\n# {doc.key}\n"
        fresh_docs[doc.key] = content
        _write_doc(tmp_path, doc.rel_path, content.replace("now", "older"))

    report = check_staleness(tmp_path, data=None,
                             renderers=_make_renderers(fresh_docs))
    assert not report.any_stale
    assert len(report.docs) == len(DOC_REGISTRY)


def test_check_staleness_detects_single_stale_doc(tmp_path):
    fresh_docs = {}
    for doc in DOC_REGISTRY:
        fresh_docs[doc.key] = f"# {doc.key}\nGenerated: fresh\nBODY-{doc.key}\n"
    # Disk copies match fresh except for rtm — intentionally mutated.
    for doc in DOC_REGISTRY:
        disk = fresh_docs[doc.key].replace("fresh", "old")
        if doc.key == "rtm":
            disk = disk.replace("BODY-rtm", "STALE-BODY")
        _write_doc(tmp_path, doc.rel_path, disk)

    report = check_staleness(tmp_path, data=None,
                             renderers=_make_renderers(fresh_docs))
    assert report.any_stale
    stale = report.stale_docs
    assert len(stale) == 1
    assert stale[0].doc == "rtm"


def test_check_staleness_doc_filter(tmp_path):
    fresh_docs = {}
    for doc in DOC_REGISTRY:
        fresh_docs[doc.key] = f"# {doc.key}\n"
        _write_doc(tmp_path, doc.rel_path, "something else\n")

    report = check_staleness(tmp_path, data=None,
                             renderers=_make_renderers(fresh_docs),
                             doc_filter=["rtm"])
    assert [d.doc for d in report.docs] == ["rtm"]


def test_check_staleness_renderer_error_captured(tmp_path):
    def boom(_data):
        raise RuntimeError("generator exploded")

    renderers = {doc.key: (boom if doc.key == "rtm" else lambda d: "ok\n")
                 for doc in DOC_REGISTRY}
    # Disk copies exist so the error isn't confused with missing file.
    for doc in DOC_REGISTRY:
        _write_doc(tmp_path, doc.rel_path, "ok\n")

    report = check_staleness(tmp_path, data=None, renderers=renderers)
    rtm = next(d for d in report.docs if d.doc == "rtm")
    assert rtm.stale is True
    assert rtm.error is not None
    assert "RuntimeError" in rtm.error


# ---------------------------------------------------------------------------
# Determinism gate (plan v7 § Group E "Determinism test required")
#
# Auto-fix must rest on deterministic generator output. If the production
# ``collect_all`` + renderers produce different bytes on two identical runs,
# Group E would spew spurious staleness findings and auto-fix would churn.
# ---------------------------------------------------------------------------


def test_collect_all_is_deterministic(project_root):
    """Two back-to-back collect_all calls on unchanged inputs produce equal data."""
    from scripts.lib.data_collector import collect_all

    a = collect_all(project_root)
    b = collect_all(project_root)

    # Timestamp differs by construction — zero it out before comparison.
    a.timestamp = ""
    b.timestamp = ""
    # Dataclass equality walks structural fields; path equality is trivial here.
    assert a.project_root == b.project_root
    assert [w for w in a.work_events] == [w for w in b.work_events]
    assert a.requirements == b.requirements
    assert a.decisions == b.decisions
    assert a.commits == b.commits
    assert a.known_failures == b.known_failures


def test_generators_deterministic_after_header_strip(project_root):
    """Twice-run renderers produce byte-identical output after header strip."""
    from scripts.audit.audit_staleness import default_renderers
    from scripts.lib.data_collector import collect_all

    data = collect_all(project_root)
    renderers = default_renderers()
    for key, render in renderers.items():
        first = normalize(render(data))
        second = normalize(render(data))
        assert first == second, f"renderer {key!r} is non-deterministic"


# ---------------------------------------------------------------------------
# update_compliance.py --check CLI
# ---------------------------------------------------------------------------


UPDATE_SCRIPT = PLUGIN_ROOT / "scripts" / "tools" / "update_compliance.py"


@pytest.mark.integration
def test_update_compliance_check_mode_writes_nothing(project_root):
    """--check returns structured JSON and does NOT touch compliance/."""
    before = {p: p.stat().st_mtime_ns
              for p in (project_root / "compliance").iterdir()
              if p.is_file()}

    result = subprocess.run(
        [sys.executable, str(UPDATE_SCRIPT),
         "--project-root", str(project_root), "--check"],
        capture_output=True, text=True, encoding="utf-8",
    )
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload["mode"] == "check"
    assert payload["success"] is True
    assert "staleness" in payload
    assert "docs" in payload["staleness"]

    # No file mtime changes in compliance/.
    after = {p: p.stat().st_mtime_ns
             for p in (project_root / "compliance").iterdir()
             if p.is_file()}
    assert before == after


def test_update_compliance_write_mode_still_requires_phase():
    """Without --check, --phase remains required (backwards compat)."""
    result = subprocess.run(
        [sys.executable, str(UPDATE_SCRIPT),
         "--project-root", "."],
        capture_output=True, text=True, encoding="utf-8",
    )
    assert result.returncode != 0
    assert "--phase" in result.stderr
