"""Tests for ``scripts.audit.audit_staleness`` pure-function helpers.

The full Group-E snapshot-provenance audit lives in
``test_audit_snapshot.py``. This file keeps:

  - ``normalize`` / ``HEADER_STRIP_RE`` unit tests (the Generated:-line
    stripper is used on BOTH sides of the snapshot byte-compare, so its
    behaviour must stay locked down).
  - The deterministic-renderer gate (``collect_all`` + the production
    renderers must remain stable on byte level across two runs, so that
    when an operator manually re-runs ``update_compliance.py`` they get
    the same output and the committed snapshot is reproducible).

Pre-iterate-2026-05-23 tests that compared on-disk vs. a fresh re-render
have been removed: the new audit no longer holds renderers — it compares
on-disk to ``git show <snapshot_sha>:<file>`` instead.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PLUGIN_ROOT))

from scripts.audit.audit_staleness import (  # noqa: E402
    HEADER_STRIP_RE,
    normalize,
)


# ---------------------------------------------------------------------------
# normalize() / HEADER_STRIP_RE — used by snapshot byte-compare
# ---------------------------------------------------------------------------


def test_header_strip_removes_generated_line():
    text = "Title\nGenerated: 2026-04-19T12:00:00Z\nBody\n"
    assert normalize(text) == "Title\nBody\n"


def test_header_strip_preserves_other_lines():
    text = "# RTM\n\nGenerated: 2026-04-19\n## Summary\nGenerated: ignore-me\n"
    # Both "Generated:" lines stripped; rest preserved verbatim.
    assert normalize(text) == "# RTM\n\n## Summary\n"


def test_header_strip_idempotent():
    text = "Generated: x\nfoo\nGenerated: y\nbar\n"
    once = normalize(text)
    twice = normalize(once)
    assert once == twice == "foo\nbar\n"


def test_header_strip_ignores_substring_matches():
    # Lines that mention "Generated:" mid-line must NOT be stripped.
    text = "Section: Generated by pipeline (note)\nbody\n"
    assert normalize(text) == text


def test_header_strip_re_is_multiline():
    # Sanity check on the exported regex itself.
    assert HEADER_STRIP_RE.flags & 8  # re.MULTILINE


# ---------------------------------------------------------------------------
# Determinism gate — production renderers must produce stable bytes
# ---------------------------------------------------------------------------


def test_collect_all_is_deterministic(project_root):
    """Two back-to-back collect_all calls on unchanged inputs produce equal data."""
    from scripts.lib.data_collector import collect_all

    a = collect_all(project_root)
    b = collect_all(project_root)

    # Timestamp differs by construction — zero it out before comparison.
    a.timestamp = ""
    b.timestamp = ""
    # Dataclass equality walks structural fields; path equality is trivial here.
    assert a.project_root == b.project_root
    assert [w for w in a.work_events] == [w for w in b.work_events]
    assert a.requirements == b.requirements
    assert a.decisions == b.decisions
    assert a.commits == b.commits
    assert a.known_failures == b.known_failures


def test_production_generators_deterministic_after_header_strip(project_root):
    """Twice-run production renderers produce byte-identical output (post header-strip).

    Not for the audit (which uses snapshot-provenance, not fresh-render)
    — for the OPERATOR who manually re-runs ``update_compliance.py``.
    They must get a stable, deterministic output so the resulting commit
    diff stays clean.
    """
    from scripts.lib.change_history import generate as render_change_history
    from scripts.lib.compliance_report import generate as render_dashboard
    from scripts.lib.data_collector import collect_all
    from scripts.lib.rtm_generator import generate as render_rtm
    from scripts.lib.sbom_generator import generate as render_sbom
    from scripts.lib.test_evidence import generate as render_test_evidence

    data = collect_all(project_root)
    renderers = {
        "rtm": render_rtm,
        "test_evidence": render_test_evidence,
        "change_history": render_change_history,
        "sbom": render_sbom,
        "dashboard": render_dashboard,
    }
    for key, render in renderers.items():
        first = normalize(render(data))
        second = normalize(render(data))
        assert first == second, f"renderer {key!r} is non-deterministic"


# ---------------------------------------------------------------------------
# update_compliance.py --check CLI contract (still routes through audit)
# ---------------------------------------------------------------------------


UPDATE_SCRIPT = PLUGIN_ROOT / "scripts" / "tools" / "update_compliance.py"


@pytest.mark.integration
def test_update_compliance_check_mode_writes_nothing(project_root):
    """--check returns structured JSON and does NOT touch .shipwright/compliance/."""
    before = {p: p.stat().st_mtime_ns
              for p in (project_root / ".shipwright" / "compliance").iterdir()
              if p.is_file()}

    result = subprocess.run(
        [sys.executable, str(UPDATE_SCRIPT),
         "--project-root", str(project_root), "--check"],
        capture_output=True, text=True, encoding="utf-8",
    )
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload["mode"] == "check"
    assert payload["success"] is True
    assert "staleness" in payload
    assert "docs" in payload["staleness"]

    # No file mtime changes in .shipwright/compliance/.
    after = {p: p.stat().st_mtime_ns
             for p in (project_root / ".shipwright" / "compliance").iterdir()
             if p.is_file()}
    assert before == after


def test_update_compliance_write_mode_still_requires_phase():
    """Without --check, --phase remains required (backwards compat)."""
    result = subprocess.run(
        [sys.executable, str(UPDATE_SCRIPT),
         "--project-root", "."],
        capture_output=True, text=True, encoding="utf-8",
    )
    assert result.returncode != 0
    assert "--phase" in result.stderr
