#!/usr/bin/env python3
"""Stop hook: Generate session_handoff.md + update dashboard + fallback phase-completion.

Automatically generates .shipwright/agent_docs/session_handoff.md from current
project state (configs, git, decision log). Non-blocking (exit 0).

Also detects if a phase completed but wasn't marked in the orchestrator
config (e.g., standalone /shipwright-build without /shipwright-run), and
triggers the compliance update as a fallback.

Usage (from hooks.json):
    uv run "${CLAUDE_PLUGIN_ROOT}/../../shared/scripts/hooks/generate_handoff_on_stop.py"
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path


# Canonical home of the agent_docs artifact set, relative to project_root.
# Mirrors agent_docs entry in shared/scripts/lib/artifact_migrations.py.
_AGENT_DOCS_DIRNAME = ".shipwright/agent_docs"

# Stop-hook writes target the gitignored runtime/ subdir; iterate-finalize
# is the single producer of the tracked variants. See
# iterate-2026-05-27-tracked-artifacts-single-producer-and-finalize-sandbox
# + shared/scripts/lib/artifact_paths.py.
_RUNTIME_SUBDIR = "runtime"


# Iterate 12.1: parse the canon frontmatter at the top of
# ``.shipwright/agent_docs/session_handoff.md``. The block is written by
# ``generate_session_handoff.py --canon-marker`` and marks the handoff
# as generated by a phase finalization step (Canon C3). If the
# frontmatter's ``run_id`` matches the current ``SHIPWRIGHT_RUN_ID``
# env var, the stop hook MUST NOT regenerate the file — doing so
# would clobber the canon handoff with a generic "session end" one
# and the iterate 12 verifier would lose the C3 artifact.
_CANON_FRONTMATTER_RE = re.compile(
    r"\A---\s*\n(.*?)\n---\s*\n",
    re.DOTALL,
)
_CANON_FIELD_RE = re.compile(
    r'^(?P<key>[a-z_]+):\s*"?(?P<value>[^"\n]*?)"?\s*$',
)


def _parse_canon_frontmatter(content: str) -> dict[str, str] | None:
    """Return the parsed canon frontmatter dict, or None.

    Only returns a dict if the top-of-file block is present AND it
    contains ``canon_generated: true``. Anything else (no frontmatter,
    manual YAML for other purposes, malformed) is treated as "no canon
    marker — regenerate as normal".
    """
    m = _CANON_FRONTMATTER_RE.match(content)
    if not m:
        return None
    block = m.group(1)
    parsed: dict[str, str] = {}
    for line in block.splitlines():
        fm = _CANON_FIELD_RE.match(line)
        if fm:
            parsed[fm.group("key")] = fm.group("value")
    if parsed.get("canon_generated", "").lower() != "true":
        return None
    return parsed


def _should_skip_regeneration(handoff_path: Path) -> tuple[bool, str]:
    """Return ``(skip, reason)``.

    Skip only when the on-disk handoff has a canon frontmatter whose
    ``run_id`` matches the current ``SHIPWRIGHT_RUN_ID`` env var. All
    other cases regenerate normally — this keeps the existing stop-hook
    contract for manual sessions and for agents that don't set the env
    var.
    """
    if not handoff_path.exists():
        return False, "no existing handoff"
    current_run_id = os.environ.get("SHIPWRIGHT_RUN_ID", "").strip()
    if not current_run_id:
        return False, "no SHIPWRIGHT_RUN_ID env — cannot match"
    try:
        existing = handoff_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False, "cannot read existing handoff"
    fm = _parse_canon_frontmatter(existing)
    if not fm:
        return False, "no canon frontmatter"
    marker_run_id = fm.get("run_id", "")
    if marker_run_id != current_run_id:
        return False, f"run_id mismatch (marker={marker_run_id!r}, current={current_run_id!r})"
    return True, f"canon marker matches run_id={current_run_id}"


def _detect_phase_complete(current_step: str, project_root: Path, completed_steps: set) -> bool:
    """Check if current phase has completed work but isn't marked complete."""
    if current_step in completed_steps:
        return False

    # Guard: skip detection during split-loop resume
    # (project+design done but plan/build cycling = mid-split-loop, stale configs)
    if current_step in ("plan", "build") and "project" in completed_steps and "design" in completed_steps:
        return False

    if current_step == "build":
        config_path = project_root / "shipwright_build_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                sections = config.get("sections", [])
                return bool(sections) and all(
                    s.get("status") == "complete" for s in sections
                )
            except (json.JSONDecodeError, OSError):
                pass
    elif current_step == "plan":
        config_path = project_root / "shipwright_plan_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                return config.get("status") == "complete"
            except (json.JSONDecodeError, OSError):
                pass
    elif current_step == "project":
        config_path = project_root / "shipwright_project_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                return config.get("status") == "complete"
            except (json.JSONDecodeError, OSError):
                pass
    elif current_step == "test":
        results_path = project_root / "shipwright_test_results.json"
        if results_path.exists():
            try:
                results = json.loads(results_path.read_text(encoding="utf-8"))
                return results.get("status") == "pass"
            except (json.JSONDecodeError, OSError):
                pass

    return False


def _run_phase_completion(project_root: Path, step: str) -> None:
    """Mark phase complete in orchestrator config (triggers compliance update)."""
    # Find orchestrator script (sibling plugin)
    scripts_dir = Path(__file__).resolve().parent.parent
    # shared/scripts/hooks -> shared -> plugins/shipwright-run
    orchestrator = scripts_dir.parent.parent / "plugins" / "shipwright-run" / "scripts" / "lib" / "orchestrator.py"

    if not orchestrator.exists():
        return

    try:
        subprocess.run(
            [sys.executable, str(orchestrator),
             "update-step", "--project-root", str(project_root),
             "--step", step, "--status", "complete"],
            capture_output=True, timeout=30,
        )
    except (subprocess.TimeoutExpired, OSError):
        pass


def _phase_task_handoff_path(project_root: Path, session_id: str) -> Path | None:
    """Return the namespaced handoff path if this session owns a v2 phase_task,
    else None (caller falls back to the generic session_handoff.md).

    F3a multi-session pipeline. Match SHIPWRIGHT_SESSION_ID against
    phase_tasks[].sessionUuid in v2 run config. No match (e.g. master
    session, standalone, v1 config) -> None.
    """
    if not session_id or session_id == "unknown":
        return None
    run_cfg = project_root / "shipwright_run_config.json"
    if not run_cfg.exists():
        return None
    try:
        config = json.loads(run_cfg.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if config.get("schemaVersion") != 2:
        return None
    run_id = config.get("runId")
    for t in config.get("phase_tasks", []):
        if t.get("sessionUuid") == session_id and run_id:
            return (
                project_root / _AGENT_DOCS_DIRNAME / "runs"
                / run_id / t.get("phaseTaskId", "unknown") / "handoff.md"
            )
    return None


def main() -> int:
    # Consume stdin (hook protocol)
    try:
        json.load(sys.stdin)
    except Exception:
        pass

    # Resolve project root — handles subdirectory projects (e.g. webui/)
    try:
        scripts_dir = Path(__file__).resolve().parent.parent
        sys.path.insert(0, str(scripts_dir))
        from lib.project_root import resolve_project_root
        project_root = resolve_project_root()
    except (ImportError, ValueError):
        project_root = Path.cwd()

    # Guard: skip if not in a shipwright-managed project
    has_run_config = (project_root / "shipwright_run_config.json").exists()
    has_agent_docs = (project_root / _AGENT_DOCS_DIRNAME).is_dir()
    has_any_config = any(
        (project_root / f).exists()
        for f in ("shipwright_project_config.json", "shipwright_plan_config.json",
                  "shipwright_build_config.json", "shipwright_events.jsonl")
    )
    if not has_run_config and not has_agent_docs and not has_any_config:
        return 0

    try:
        # Import the shared generator
        scripts_dir = Path(__file__).resolve().parent.parent
        sys.path.insert(0, str(scripts_dir))
        from tools.generate_session_handoff import generate_handoff

        agent_docs = project_root / _AGENT_DOCS_DIRNAME
        runtime_dir = agent_docs / _RUNTIME_SUBDIR
        # Tracked path — what the canon-frontmatter skip check inspects
        # (and what iterate-finalize writes). The runtime variant is the
        # Stop-hook's actual write target post-2026-05-27.
        tracked_handoff = agent_docs / "session_handoff.md"
        handoff_path = runtime_dir / "session_handoff.md"

        # Iterate 12.1 — conditional skip: when a phase finalization just
        # wrote the TRACKED handoff with --canon-marker and its frontmatter
        # run_id matches the current SHIPWRIGHT_RUN_ID, leave the runtime
        # write off too. Without this guard the Stop hook fires at turn end
        # and would re-shadow the canon handoff in runtime/, which the
        # iterate 12 verifier (reading tracked) doesn't care about — but
        # keeping the skip in place preserves the existing semantics for
        # consumers that fall back from tracked to runtime.
        skip, skip_reason = _should_skip_regeneration(tracked_handoff)
        if skip:
            # Stop hookSpecificOutput cannot carry additionalContext; emit
            # to stderr instead. See ADR-042.
            sys.stderr.write(
                f"[shipwright:handoff] regeneration skipped: {skip_reason}\n"
            )
            return 0

        session_id = os.environ.get("SHIPWRIGHT_SESSION_ID", "unknown")
        content = generate_handoff(project_root, session_id, reason="session end")

        # F3a multi-session pipeline: if this session is claimed by a
        # phase_task in a v2 run config, namespace the handoff under
        # .shipwright/agent_docs/runs/<runId>/<phaseTaskId>/handoff.md instead of
        # clobbering the generic session_handoff.md (which the master
        # session owns).
        phase_namespaced = _phase_task_handoff_path(project_root, session_id)

        loop_id = os.environ.get("SHIPWRIGHT_LOOP_ID")
        loop_unit = os.environ.get("SHIPWRIGHT_LOOP_UNIT_ID")
        if loop_id and loop_unit:
            namespaced_dir = project_root / ".shipwright" / "planning" / "handoffs" / loop_id
            namespaced_dir.mkdir(parents=True, exist_ok=True)
            namespaced_path = namespaced_dir / f"{loop_unit}.md"
            namespaced_path.write_text(content, encoding="utf-8")
            handoff_path = namespaced_path
        elif phase_namespaced is not None:
            phase_namespaced.parent.mkdir(parents=True, exist_ok=True)
            phase_namespaced.write_text(content, encoding="utf-8")
            handoff_path = phase_namespaced
        else:
            # Write to gitignored runtime/ subdir. Iterate-finalize will
            # copy this to the tracked path at F5b.
            runtime_dir.mkdir(parents=True, exist_ok=True)
            handoff_path.write_text(content, encoding="utf-8")

        # Update build dashboard with "paused" status — also writes to
        # runtime/. The tracked dashboard is written exclusively by
        # iterate-finalize.
        try:
            from tools.update_build_dashboard import generate_dashboard

            dashboard = generate_dashboard(
                project_root, status="paused", session_id=session_id,
            )
            runtime_dir.mkdir(parents=True, exist_ok=True)
            (runtime_dir / "build_dashboard.md").write_text(dashboard, encoding="utf-8")
        except Exception:
            pass  # Dashboard update is best-effort

        # Compliance MDs are NEVER written by this Stop hook.
        # iterate-2026-05-23-compliance-md-single-producer makes
        # iterate-finalize the sole producer of .shipwright/compliance/*.md;
        # the snapshot audit (audit_staleness) verifies on-disk against the
        # last iterate-finalize commit. Out-of-band auto-regen here caused
        # dirty-tree noise on every Stop event in non-iterate sessions
        # (security work, manual fixes) and wrote MDs using whatever
        # events.jsonl the local machine had — frequently behind what was
        # in HEAD on a multi-machine project. Deleted as a class of bug,
        # not just one heuristic.

        # Fallback: detect incomplete phase-completion and trigger it
        try:
            run_config_path = project_root / "shipwright_run_config.json"
            if run_config_path.exists():
                run_config = json.loads(run_config_path.read_text(encoding="utf-8"))
                current_step = run_config.get("current_step")
                completed_steps = set(run_config.get("completed_steps", []))

                if current_step and _detect_phase_complete(current_step, project_root, completed_steps):
                    _run_phase_completion(project_root, current_step)
        except Exception:
            pass  # Phase-completion fallback is best-effort

        relative_path = handoff_path.relative_to(project_root) if handoff_path.is_relative_to(project_root) else handoff_path
        sys.stderr.write(
            f"[shipwright:handoff] generated at {relative_path}\n"
        )
    except Exception as e:
        # Never block session end — report failure to stderr.
        sys.stderr.write(
            f"[shipwright:handoff] generation skipped: {type(e).__name__}: {e}\n"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
