#!/usr/bin/env python3
"""Stop hook: Generate session_handoff.md + update dashboard + fallback phase-completion.

Automatically generates agent_docs/session_handoff.md from current
project state (configs, git, decision log). Non-blocking (exit 0).

Also detects if a phase completed but wasn't marked in the orchestrator
config (e.g., standalone /shipwright-build without /shipwright-run), and
triggers the compliance update as a fallback.

Usage (from hooks.json):
    uv run ${CLAUDE_PLUGIN_ROOT}/../../shared/scripts/hooks/generate_handoff_on_stop.py
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path


# Iterate 12.1: parse the canon frontmatter at the top of
# ``agent_docs/session_handoff.md``. The block is written by
# ``generate_session_handoff.py --canon-marker`` and marks the handoff
# as generated by a phase finalization step (Canon C3). If the
# frontmatter's ``run_id`` matches the current ``SHIPWRIGHT_RUN_ID``
# env var, the stop hook MUST NOT regenerate the file — doing so
# would clobber the canon handoff with a generic "session end" one
# and the iterate 12 verifier would lose the C3 artifact.
_CANON_FRONTMATTER_RE = re.compile(
    r"\A---\s*\n(.*?)\n---\s*\n",
    re.DOTALL,
)
_CANON_FIELD_RE = re.compile(
    r'^(?P<key>[a-z_]+):\s*"?(?P<value>[^"\n]*?)"?\s*$',
)


def _parse_canon_frontmatter(content: str) -> dict[str, str] | None:
    """Return the parsed canon frontmatter dict, or None.

    Only returns a dict if the top-of-file block is present AND it
    contains ``canon_generated: true``. Anything else (no frontmatter,
    manual YAML for other purposes, malformed) is treated as "no canon
    marker — regenerate as normal".
    """
    m = _CANON_FRONTMATTER_RE.match(content)
    if not m:
        return None
    block = m.group(1)
    parsed: dict[str, str] = {}
    for line in block.splitlines():
        fm = _CANON_FIELD_RE.match(line)
        if fm:
            parsed[fm.group("key")] = fm.group("value")
    if parsed.get("canon_generated", "").lower() != "true":
        return None
    return parsed


def _should_skip_regeneration(handoff_path: Path) -> tuple[bool, str]:
    """Return ``(skip, reason)``.

    Skip only when the on-disk handoff has a canon frontmatter whose
    ``run_id`` matches the current ``SHIPWRIGHT_RUN_ID`` env var. All
    other cases regenerate normally — this keeps the existing stop-hook
    contract for manual sessions and for agents that don't set the env
    var.
    """
    if not handoff_path.exists():
        return False, "no existing handoff"
    current_run_id = os.environ.get("SHIPWRIGHT_RUN_ID", "").strip()
    if not current_run_id:
        return False, "no SHIPWRIGHT_RUN_ID env — cannot match"
    try:
        existing = handoff_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False, "cannot read existing handoff"
    fm = _parse_canon_frontmatter(existing)
    if not fm:
        return False, "no canon frontmatter"
    marker_run_id = fm.get("run_id", "")
    if marker_run_id != current_run_id:
        return False, f"run_id mismatch (marker={marker_run_id!r}, current={current_run_id!r})"
    return True, f"canon marker matches run_id={current_run_id}"


def _detect_phase_complete(current_step: str, project_root: Path, completed_steps: set) -> bool:
    """Check if current phase has completed work but isn't marked complete."""
    if current_step in completed_steps:
        return False

    # Guard: skip detection during split-loop resume
    # (project+design done but plan/build cycling = mid-split-loop, stale configs)
    if current_step in ("plan", "build") and "project" in completed_steps and "design" in completed_steps:
        return False

    if current_step == "build":
        config_path = project_root / "shipwright_build_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                sections = config.get("sections", [])
                return bool(sections) and all(
                    s.get("status") == "complete" for s in sections
                )
            except (json.JSONDecodeError, OSError):
                pass
    elif current_step == "plan":
        config_path = project_root / "shipwright_plan_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                return config.get("status") == "complete"
            except (json.JSONDecodeError, OSError):
                pass
    elif current_step == "project":
        config_path = project_root / "shipwright_project_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                return config.get("status") == "complete"
            except (json.JSONDecodeError, OSError):
                pass
    elif current_step == "test":
        results_path = project_root / "shipwright_test_results.json"
        if results_path.exists():
            try:
                results = json.loads(results_path.read_text(encoding="utf-8"))
                return results.get("status") == "pass"
            except (json.JSONDecodeError, OSError):
                pass

    return False


def _run_phase_completion(project_root: Path, step: str) -> None:
    """Mark phase complete in orchestrator config (triggers compliance update)."""
    # Find orchestrator script (sibling plugin)
    scripts_dir = Path(__file__).resolve().parent.parent
    # shared/scripts/hooks -> shared -> plugins/shipwright-run
    orchestrator = scripts_dir.parent.parent / "plugins" / "shipwright-run" / "scripts" / "lib" / "orchestrator.py"

    if not orchestrator.exists():
        return

    try:
        subprocess.run(
            [sys.executable, str(orchestrator),
             "update-step", "--project-root", str(project_root),
             "--step", step, "--status", "complete"],
            capture_output=True, timeout=30,
        )
    except (subprocess.TimeoutExpired, OSError):
        pass


def main() -> int:
    # Consume stdin (hook protocol)
    try:
        json.load(sys.stdin)
    except Exception:
        pass

    # Resolve project root — handles subdirectory projects (e.g. webui/)
    try:
        scripts_dir = Path(__file__).resolve().parent.parent
        sys.path.insert(0, str(scripts_dir))
        from lib.project_root import resolve_project_root
        project_root = resolve_project_root()
    except (ImportError, ValueError):
        project_root = Path.cwd()

    # Guard: skip if not in a shipwright-managed project
    has_run_config = (project_root / "shipwright_run_config.json").exists()
    has_agent_docs = (project_root / "agent_docs").is_dir()
    has_any_config = any(
        (project_root / f).exists()
        for f in ("shipwright_project_config.json", "shipwright_plan_config.json",
                  "shipwright_build_config.json", "shipwright_events.jsonl")
    )
    if not has_run_config and not has_agent_docs and not has_any_config:
        return 0

    try:
        # Import the shared generator
        scripts_dir = Path(__file__).resolve().parent.parent
        sys.path.insert(0, str(scripts_dir))
        from tools.generate_session_handoff import generate_handoff

        agent_docs = project_root / "agent_docs"
        handoff_path = agent_docs / "session_handoff.md"

        # Iterate 12.1 — conditional skip: when a phase finalization just
        # wrote the handoff with --canon-marker and its frontmatter
        # run_id matches the current SHIPWRIGHT_RUN_ID, leave it alone.
        # Without this guard the Stop hook fires at turn end and
        # clobbers the canon handoff with a generic "session end" one,
        # which the iterate 12 verifier would then flag as missing C3.
        skip, skip_reason = _should_skip_regeneration(handoff_path)
        if skip:
            print(json.dumps({
                "hookSpecificOutput": {
                    "hookEventName": "Stop",
                    "additionalContext": (
                        f"Session handoff regeneration skipped: {skip_reason}"
                    ),
                }
            }))
            return 0

        session_id = os.environ.get("SHIPWRIGHT_SESSION_ID", "unknown")
        content = generate_handoff(project_root, session_id, reason="session end")

        loop_id = os.environ.get("SHIPWRIGHT_LOOP_ID")
        loop_unit = os.environ.get("SHIPWRIGHT_LOOP_UNIT_ID")
        if loop_id and loop_unit:
            namespaced_dir = project_root / "planning" / "handoffs" / loop_id
            namespaced_dir.mkdir(parents=True, exist_ok=True)
            namespaced_path = namespaced_dir / f"{loop_unit}.md"
            namespaced_path.write_text(content, encoding="utf-8")
            handoff_path = namespaced_path
        else:
            agent_docs.mkdir(exist_ok=True)
            handoff_path.write_text(content, encoding="utf-8")

        # Update build dashboard with "paused" status
        try:
            from tools.update_build_dashboard import generate_dashboard

            dashboard = generate_dashboard(
                project_root, status="paused", session_id=session_id,
            )
            (agent_docs / "build_dashboard.md").write_text(dashboard, encoding="utf-8")
        except Exception:
            pass  # Dashboard update is best-effort

        # Update compliance docs (best-effort, idempotent)
        try:
            compliance_dashboard = project_root / "compliance" / "dashboard.md"
            run_cfg = project_root / "shipwright_run_config.json"
            needs_update = (
                run_cfg.exists()
                and (not compliance_dashboard.exists()
                     or compliance_dashboard.stat().st_mtime < run_cfg.stat().st_mtime)
            )
            if needs_update:
                compliance_plugin = Path(__file__).resolve().parents[3] / "plugins" / "shipwright-compliance"
                update_script = compliance_plugin / "scripts" / "tools" / "update_compliance.py"
                if update_script.exists():
                    phase = "iterate"
                    if has_run_config:
                        try:
                            cfg_data = json.loads(run_cfg.read_text(encoding="utf-8"))
                            phase = cfg_data.get("current_step", "iterate")
                        except (json.JSONDecodeError, OSError):
                            pass
                    subprocess.run(
                        [sys.executable, str(update_script),
                         "--project-root", str(project_root),
                         "--phase", phase],
                        capture_output=True, timeout=30,
                    )
        except Exception:
            pass  # Compliance update is best-effort

        # Fallback: detect incomplete phase-completion and trigger it
        try:
            run_config_path = project_root / "shipwright_run_config.json"
            if run_config_path.exists():
                run_config = json.loads(run_config_path.read_text(encoding="utf-8"))
                current_step = run_config.get("current_step")
                completed_steps = set(run_config.get("completed_steps", []))

                if current_step and _detect_phase_complete(current_step, project_root, completed_steps):
                    _run_phase_completion(project_root, current_step)
        except Exception:
            pass  # Phase-completion fallback is best-effort

        relative_path = handoff_path.relative_to(project_root) if handoff_path.is_relative_to(project_root) else handoff_path
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "Stop",
                "additionalContext": f"Session handoff generated at {relative_path}",
            }
        }))
    except Exception as e:
        # Never block session end — report failure as info
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "Stop",
                "additionalContext": f"Session handoff generation skipped: {e}",
            }
        }))

    return 0


if __name__ == "__main__":
    sys.exit(main())
