#!/usr/bin/env python3
"""Stop hook: Generate session_handoff.md + update dashboard + fallback phase-completion.

Automatically generates .shipwright/agent_docs/session_handoff.md from current
project state (configs, git, decision log). Non-blocking (exit 0).

Also detects if a phase completed but wasn't marked in the orchestrator
config (e.g., standalone /shipwright-build without /shipwright-run), and
triggers the compliance update as a fallback.

Usage (from hooks.json):
    uv run "${CLAUDE_PLUGIN_ROOT}/../../shared/scripts/hooks/generate_handoff_on_stop.py"
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_SCRIPTS_ROOT = Path(__file__).resolve().parent.parent
if str(_SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_ROOT))

# Canonical greenfield/foreign predicate — single SSoT every hook shares.
from lib.atomic_write import durable_atomic_write  # noqa: E402
from lib.canon_frontmatter import parse_canon_frontmatter  # noqa: E402
from lib.file_lock import LockTimeout, file_lock  # noqa: E402
from lib.handoff_phase_status import (  # noqa: E402
    phase_tasks_has_usable_entries as _phase_tasks_has_usable_entries,
    phase_tasks_progress as _phase_tasks_progress,
)
from lib.project_root import is_shipwright_project, resolve_project_root  # noqa: E402

_RUN_CONFIG_NAME = "shipwright_run_config.json"
# Matches orchestrator_pkg/run_config_store.py's LOCK_NAME — the same
# advisory lock every other shipwright_run_config.json writer coordinates
# through. Not imported (plugin-local, ADR-045 lib collision): a bare
# filename suffix is a safe duplication.
_RUN_CONFIG_LOCK_NAME = _RUN_CONFIG_NAME + ".lock"


# Canonical home of the agent_docs artifact set, relative to project_root.
# Mirrors agent_docs entry in shared/scripts/lib/artifact_migrations.py.
_AGENT_DOCS_DIRNAME = ".shipwright/agent_docs"

# Stop-hook writes target the gitignored runtime/ subdir; iterate-finalize
# is the single producer of the tracked variants. See
# iterate-2026-05-27-tracked-artifacts-single-producer-and-finalize-sandbox
# + shared/scripts/lib/artifact_paths.py.
_RUNTIME_SUBDIR = "runtime"


# Iterate 12.1: parse the canon frontmatter at the top of
# ``.shipwright/agent_docs/session_handoff.md``. The block is written by
# ``generate_session_handoff.py --canon-marker`` and marks the handoff
# as generated by a phase finalization step (Canon C3). If the
# frontmatter's ``run_id`` matches the current ``SHIPWRIGHT_RUN_ID``
# env var, the stop hook MUST NOT regenerate the file — doing so
# would clobber the canon handoff with a generic "session end" one
# and the iterate 12 verifier would lose the C3 artifact.
# The parser moved to ``lib.canon_frontmatter`` in
# iterate-2026-07-27-name-the-blocker, when the F11 freshness verifier became a
# second reader of the same block. Re-exported under the old private name so
# this module's existing callers and tests are unaffected.
_parse_canon_frontmatter = parse_canon_frontmatter


def _should_skip_regeneration(handoff_path: Path) -> tuple[bool, str]:
    """Return ``(skip, reason)``.

    Skip only when the on-disk handoff has a canon frontmatter whose
    ``run_id`` matches the current ``SHIPWRIGHT_RUN_ID`` env var. All
    other cases regenerate normally — this keeps the existing stop-hook
    contract for manual sessions and for agents that don't set the env
    var.
    """
    if not handoff_path.exists():
        return False, "no existing handoff"
    current_run_id = os.environ.get("SHIPWRIGHT_RUN_ID", "").strip()
    if not current_run_id:
        return False, "no SHIPWRIGHT_RUN_ID env — cannot match"
    try:
        existing = handoff_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False, "cannot read existing handoff"
    fm = _parse_canon_frontmatter(existing)
    if not fm:
        return False, "no canon frontmatter"
    marker_run_id = fm.get("run_id", "")
    if marker_run_id != current_run_id:
        return False, f"run_id mismatch (marker={marker_run_id!r}, current={current_run_id!r})"
    return True, f"canon marker matches run_id={current_run_id}"


def _detect_phase_complete(current_phase: str, project_root: Path, completed_phases: set) -> bool:
    """Check if current phase has completed work but isn't marked complete."""
    if current_phase in completed_phases:
        return False

    # Guard: skip detection during split-loop resume
    # (project+design done but plan/build cycling = mid-split-loop, stale configs)
    if current_phase in ("plan", "build") and "project" in completed_phases and "design" in completed_phases:
        return False

    if current_phase == "build":
        config_path = project_root / "shipwright_build_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                sections = config.get("sections", [])
                return bool(sections) and all(
                    s.get("status") == "complete" for s in sections
                )
            except (json.JSONDecodeError, OSError):
                pass
    elif current_phase == "plan":
        config_path = project_root / "shipwright_plan_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                return config.get("status") == "complete"
            except (json.JSONDecodeError, OSError):
                pass
    elif current_phase == "project":
        config_path = project_root / "shipwright_project_config.json"
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text(encoding="utf-8"))
                return config.get("status") == "complete"
            except (json.JSONDecodeError, OSError):
                pass
    elif current_phase == "test":
        results_path = project_root / "shipwright_test_results.json"
        if results_path.exists():
            try:
                results = json.loads(results_path.read_text(encoding="utf-8"))
                return results.get("status") == "pass"
            except (json.JSONDecodeError, OSError):
                pass

    return False


def _build_legacy_phase_task(phase: str, status: str, now: str) -> dict[str, Any]:
    """A full-shape ``phase_tasks[]`` entry for a phase recovered from legacy
    ``current_step``/``completed_steps``, used only by the one-time cutover
    below. Mirrors ``config_factory.build_v1_phase_task(phase, status,
    now=...)`` field-for-field, terminal/active logic included (not
    imported: ADR-045 lib collision, same tradeoff as
    ``write_run_config._build_v1_style_phase_task_seed``).
    """
    terminal = status in {"done", "failed", "skipped"}
    active = status not in {"backlog", "awaiting_launch"}
    return {
        "phaseTaskId": "ptk-" + uuid.uuid4().hex[:8],
        "phase": phase,
        "splitId": None,
        "sessionUuid": str(uuid.uuid4()),
        "version": 1,
        "status": status,
        "title": phase,
        "description": (
            "Advanced via the v1 update_step path (standalone / legacy / "
            "adopted run, no orchestrator session)."
        ),
        "slashCommand": f"/shipwright-{phase}",
        "prerequisites": [],
        "claimedBySessionUuid": None,
        "claimAttemptedAt": None,
        "executionCount": 1 if active else 0,
        "createdAt": now,
        "awaitingLaunchAt": None,
        "startedAt": now if active else None,
        "completedAt": now if terminal else None,
        "result": None,
        "errors": [],
    }


def _seed_legacy_phase_task_history(
    project_root: Path, done_phases: list[str], current_phase: str | None,
) -> None:
    """Locked + atomic read-modify-write: append a ``done`` phase_tasks[]
    entry for every phase in ``done_phases`` without one already, PLUS an
    ``in_progress`` entry for ``current_phase`` if it has none.

    Only called from the one-time legacy cutover in ``main()`` — the sole
    chance to carry ``completed_steps`` history forward, since the cutover
    self-disables once ``phase_tasks[]`` gains usable entries. Seeding
    ``current_phase`` too (not just the historical phases) closes a
    doubt-review round-2 finding: seeding ONLY the historical phases could
    flip ``phase_tasks_has_usable_entries()`` True — self-disabling the
    cutover — before ``current_phase`` itself ever got a ``phase_tasks[]``
    entry, permanently orphaning whichever phase was actually in flight at
    cutover time. If it also completes this same invocation,
    ``_run_phase_completion``'s ``update-step`` call below finds this seed
    (matches on phase + splitId=None, same as ``_upsert_v1_phase_task``
    everywhere else) and mutates it to ``done`` in place.

    Locked (``lib.file_lock`` on the same ``*.lock`` path
    ``orchestrator_pkg/run_config_store.py`` uses — every other
    ``shipwright_run_config.json`` writer coordinates through that same
    path) and atomic (``lib.atomic_write``) — round-1 of this same doubt
    review flagged a bare, unlocked ``write_text`` here as unlike every
    other writer of this file, which this codebase treats as
    lock-and-atomic-write-protected (``config_io.save_run_config``'s own
    docstring). Re-reads the file fresh under the lock rather than reusing
    a copy read before the lock was taken, closing that same race window.
    Best-effort: any failure here just means the next Stop-hook invocation
    retries the cutover.
    """
    run_config_path = project_root / _RUN_CONFIG_NAME
    lock_path = project_root / _RUN_CONFIG_LOCK_NAME
    now = datetime.now(timezone.utc).isoformat()
    try:
        with file_lock(lock_path, timeout_seconds=10.0):
            if not run_config_path.exists():
                return
            run_config = json.loads(run_config_path.read_text(encoding="utf-8"))
            tasks = run_config.get("phase_tasks")
            tasks = list(tasks) if isinstance(tasks, list) else []
            existing_phases = {
                t.get("phase") for t in tasks
                if isinstance(t, dict) and t.get("splitId") is None
            }
            for phase in done_phases:
                if phase in existing_phases:
                    continue
                tasks.append(_build_legacy_phase_task(phase, "done", now))
            if current_phase and current_phase not in existing_phases:
                tasks.append(
                    _build_legacy_phase_task(current_phase, "in_progress", now),
                )
            run_config["phase_tasks"] = tasks
            durable_atomic_write(
                run_config_path, json.dumps(run_config, indent=2) + "\n",
            )
    except (LockTimeout, OSError, json.JSONDecodeError):
        pass


def _run_phase_completion(project_root: Path, step: str) -> None:
    """Mark phase complete in orchestrator config (triggers compliance update)."""
    # Find orchestrator script (sibling plugin)
    scripts_dir = Path(__file__).resolve().parent.parent
    # shared/scripts/hooks -> shared -> plugins/shipwright-run
    orchestrator = scripts_dir.parent.parent / "plugins" / "shipwright-run" / "scripts" / "lib" / "orchestrator.py"

    if not orchestrator.exists():
        return

    try:
        subprocess.run(
            [sys.executable, str(orchestrator),
             "update-step", "--project-root", str(project_root),
             "--step", step, "--status", "complete"],
            capture_output=True, timeout=90,  # strictly > inner compliance 60s, so update_step survives to save_run_config (WP2/F13)
        )
    except (subprocess.TimeoutExpired, OSError):
        pass


def main() -> int:
    # Consume stdin (hook protocol)
    try:
        json.load(sys.stdin)
    except Exception:
        pass

    # Resolve project root — handles subdirectory projects (e.g. webui/)
    try:
        project_root = resolve_project_root()
    except ValueError:
        project_root = Path.cwd()

    # Guard: skip if not in a shipwright-managed project (canonical predicate —
    # every Stop hook shares one greenfield/foreign boundary,
    # iterate-2026-06-12-canonical-project-predicate).
    if not is_shipwright_project(project_root):
        return 0

    try:
        # Import the shared generator
        scripts_dir = Path(__file__).resolve().parent.parent
        sys.path.insert(0, str(scripts_dir))
        from tools.generate_session_handoff import generate_handoff

        agent_docs = project_root / _AGENT_DOCS_DIRNAME
        runtime_dir = agent_docs / _RUNTIME_SUBDIR
        # Tracked path — what the canon-frontmatter skip check inspects
        # (and what iterate-finalize writes). The runtime variant is the
        # Stop-hook's actual write target post-2026-05-27.
        tracked_handoff = agent_docs / "session_handoff.md"
        handoff_path = runtime_dir / "session_handoff.md"

        # Iterate 12.1 — conditional skip: when a phase finalization just
        # wrote the TRACKED handoff with --canon-marker and its frontmatter
        # run_id matches the current SHIPWRIGHT_RUN_ID, leave the runtime
        # write off too. Without this guard the Stop hook fires at turn end
        # and would re-shadow the canon handoff in runtime/, which the
        # iterate 12 verifier (reading tracked) doesn't care about — but
        # keeping the skip in place preserves the existing semantics for
        # consumers that fall back from tracked to runtime.
        skip, skip_reason = _should_skip_regeneration(tracked_handoff)
        if skip:
            # Stop hookSpecificOutput cannot carry additionalContext; emit
            # to stderr instead. See ADR-042.
            sys.stderr.write(
                f"[shipwright:handoff] regeneration skipped: {skip_reason}\n"
            )
            return 0

        session_id = os.environ.get("SHIPWRIGHT_SESSION_ID", "unknown")

        # Once-per-(Stop, session) dedup of the ~11× fan-out's identical handoff
        # regen (after greenfield + canon-skip guards). See claim_once_for_event.
        from lib.event_once import claim_once_for_event
        if not claim_once_for_event(project_root, "stop-handoff", session_id):
            return 0

        content = generate_handoff(project_root, session_id, reason="session end")

        # A phase-namespaced handoff branch used to fire under the removed
        # multi_session mode; single_session never matches it. Removed with
        # the engine (iterate-2026-07-14-remove-multi-session).
        loop_id = os.environ.get("SHIPWRIGHT_LOOP_ID")
        loop_unit = os.environ.get("SHIPWRIGHT_LOOP_UNIT_ID")
        if loop_id and loop_unit:
            namespaced_dir = project_root / ".shipwright" / "planning" / "handoffs" / loop_id
            namespaced_dir.mkdir(parents=True, exist_ok=True)
            namespaced_path = namespaced_dir / f"{loop_unit}.md"
            namespaced_path.write_text(content, encoding="utf-8")
            handoff_path = namespaced_path
        else:
            # Write to gitignored runtime/ subdir. Iterate-finalize will
            # copy this to the tracked path at F5b.
            runtime_dir.mkdir(parents=True, exist_ok=True)
            handoff_path.write_text(content, encoding="utf-8")

        # Update build dashboard with "paused" status — also writes to
        # runtime/. The tracked dashboard is written exclusively by
        # iterate-finalize.
        try:
            from tools.update_build_dashboard import generate_dashboard

            dashboard = generate_dashboard(
                project_root, status="paused", session_id=session_id,
            )
            runtime_dir.mkdir(parents=True, exist_ok=True)
            (runtime_dir / "build_dashboard.md").write_text(dashboard, encoding="utf-8")
        except Exception:
            pass  # Dashboard update is best-effort

        # Compliance MDs are NEVER written by this Stop hook
        # (iterate-2026-05-23-compliance-md-single-producer): iterate-finalize
        # is the sole producer of .shipwright/compliance/*.md.

        # Fallback: detect incomplete phase-completion and trigger it
        try:
            run_config_path = project_root / _RUN_CONFIG_NAME
            if run_config_path.exists():
                run_config = json.loads(run_config_path.read_text(encoding="utf-8"))

                # phase_tasks[] (v2) is the SOLE authority for progress — the
                # write-once current_step/completed_steps fields are retired
                # (campaign p4-04-retire-write-once-steps, sub-iterate s5).
                current_phase, completed_phases = _phase_tasks_progress(run_config)

                # One-time cutover (external code review, GLM HIGH): this is
                # what triggers update-step, which seeds phase_tasks[] — a
                # PRE-s5 (legacy-only) config would otherwise never self-heal.
                # Mirrors config_factory.create_config's identical boundary.
                if current_phase is None and not _phase_tasks_has_usable_entries(run_config):
                    legacy_current = run_config.get("current_step")
                    if isinstance(legacy_current, str):
                        current_phase = legacy_current
                        legacy_steps = run_config.get("completed_steps")
                        completed_phases = (
                            {s for s in legacy_steps if isinstance(s, str)}
                            if isinstance(legacy_steps, list) else set()
                        )
                        # Seed history for every OTHER recovered phase, PLUS
                        # an in_progress placeholder for current_phase itself
                        # — not just the one phase update-step marks complete
                        # below (doubt review, s5) — this cutover never fires
                        # again once phase_tasks[] has usable entries, so
                        # current_phase must get one of its own here too, or
                        # it is permanently orphaned the moment the seed
                        # below makes the OTHER entries usable.
                        historical_phases = sorted(completed_phases - {current_phase})
                        _seed_legacy_phase_task_history(
                            project_root, historical_phases, current_phase,
                        )

                if current_phase and _detect_phase_complete(current_phase, project_root, completed_phases):
                    _run_phase_completion(project_root, current_phase)
        except Exception:
            pass  # Phase-completion fallback is best-effort

        relative_path = handoff_path.relative_to(project_root) if handoff_path.is_relative_to(project_root) else handoff_path
        sys.stderr.write(
            f"[shipwright:handoff] generated at {relative_path}\n"
        )
    except Exception as e:
        # Never block session end — report failure to stderr.
        sys.stderr.write(
            f"[shipwright:handoff] generation skipped: {type(e).__name__}: {e}\n"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
