"""Seed `.shipwright/planning/adr/` with adopt's own minted ADRs.

Split out of `artifact_writer.py` (grandfathered at its own bloat ceiling).
`write_agent_docs` calls into this module and re-exports the names used.

trg-50efc4c8: nothing seeded `ADR_SPEC_FOLDER` — `_seed_adr_spec_folder`
fixes that. trg-6b59524b: a retroactive ADR with a body but no subject/sha
rendered as `(no subject)` and reported success regardless —
`_resolve_retroactive_adrs` fails closed, deriving via
`_derive_commit_subject` where possible. Harvested third-party ADRs (see
`prior_art_harvester.py`) are never seeded here — only what adopt minted.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from lib.preserve_existing import preserve_if_exists, record_preservation_action

# Mirrors shared/scripts/lib/adr_index.py + write_decision_log.py, which
# each define this same string independently rather than cross the
# plugin/shared boundary (the `lib` collision `_refresh_adr_index` works around).
ADR_SPEC_FOLDER = ".shipwright/planning/adr"

#: Git's own minimum abbreviation (4 chars, either case) — the documented
#: enrichment example is a 6-char `commit_sha`. Guards a `git log` call,
#: not a stored identity (unlike artifact_writer's stricter `_COMMIT_SHA_RE`).
_COMMIT_SHA_RE = re.compile(r"^[0-9a-fA-F]{4,40}$")


def _adoption_adr_fields(*, features_count: int, profile: str, scope: str) -> dict[str, str]:
    """The adoption ADR's prose, single-sourced between its inline
    `decision_log.md` entry and its seeded `.shipwright/planning/adr/` file
    so neither can silently drift from the other."""
    return {
        "context": (
            f"This repository existed with {features_count} detected feature(s) and "
            "substantive git history before /shipwright-adopt ran. The goal is to "
            "bring it under the Shipwright SDLC (CLAUDE.md + .shipwright/agent_docs + "
            ".shipwright/planning/ + .shipwright/compliance/ + configs) without "
            "disrupting the existing codebase."
        ),
        "decision": (
            f"Adopted into Shipwright using profile `{profile}` and scope `{scope}`. "
            'Retroactively marked `completed_steps = ["project", "plan", "build", '
            '"test"]` so that `/shipwright-iterate` and downstream skills '
            "(`/shipwright-compliance`, `/shipwright-test`) work as on a "
            "natively-built project."
        ),
        "consequences": (
            "- Future changes MUST go through `/shipwright-iterate` (not "
            "`/shipwright-project`/`/shipwright-plan`/`/shipwright-build`).\n"
            "- Compliance reports (RTM, SBOM, change-history) are seeded; "
            "test-evidence starts collecting from the first `/shipwright-test` run.\n"
            "- Any existing E2E baseline auto-generated by Adopt (under "
            "`e2e/flows/adopted-baseline.spec.ts`) is a regression guard, not a "
            "substitute for real acceptance tests."
        ),
        "rejected": (
            "- Manual `/shipwright-project` init: would lose git history and force "
            "re-description of existing code.\n"
            "- No adoption (ad-hoc `/shipwright-iterate`): would mean missing "
            "configs, no compliance reports, and the audit pipeline would "
            "silently no-op."
        ),
    }


def _derive_commit_subject(project_root: Path, sha: str) -> str:
    """Look up a commit's subject via git. Returns ``""`` (never raises)."""
    if not _COMMIT_SHA_RE.match(sha):
        return ""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%s", sha],
            cwd=project_root,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
            check=False,
        )
    except (subprocess.SubprocessError, OSError):
        return ""
    if result.returncode != 0:
        return ""
    return result.stdout.strip()


def _resolve_retroactive_adrs(
    project_root: Path, retroactive_adrs: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Fill in a missing ``subject`` from the commit it names, and fail
    closed on any retroactive ADR still missing subject/context/decision
    (trg-6b59524b). ``consequences`` stays soft (em-dash default)."""
    resolved: list[dict[str, Any]] = []
    errors: list[str] = []
    for i, adr in enumerate(retroactive_adrs):
        # `commit_sha` is the documented Layer-2 key; `sha` is what downstream readers here use.
        sha = str(adr.get("sha") or adr.get("commit_sha") or "").strip()
        subject = str(adr.get("subject") or "").strip()
        if not subject and sha:
            subject = _derive_commit_subject(project_root, sha)
        context = str(adr.get("context") or "").strip()
        decision = str(adr.get("decision") or "").strip()
        missing = [
            name for name, val in
            (("subject", subject), ("context", context), ("decision", decision))
            if not val
        ]
        if missing:
            errors.append(
                f"adrs[{i}] (sha={sha or 'unknown'}): missing {', '.join(missing)}"
            )
            continue
        merged = dict(adr)
        merged["sha"] = sha
        merged["subject"] = subject
        merged["context"] = context
        merged["decision"] = decision
        merged["consequences"] = str(adr.get("consequences") or "").strip() or "—"
        resolved.append(merged)
    if errors:
        bullet = "\n  - ".join(errors)
        raise ValueError(
            "Layer-2 enrichment produced hollow retroactive ADR(s) - a missing "
            "subject/context/decision would render as an honest-looking heading "
            "over an empty body, and adoption must not report success over "
            "that:\n  - " + bullet + "\n"
            "Re-run Layer-2 enrichment, or fill in the missing field(s) in "
            ".shipwright/adopt/enrichment.json and re-run Step E."
        )
    return resolved


_ADR_SLUG_STRIP_RE = re.compile(r"[^a-z0-9]+")


def _adr_slug(subject: str) -> str:
    """Filesystem-safe slug for an ADR spec filename — matches the
    ``<NNN>-<slug>.md`` convention ``shared/scripts/lib/adr_index.py``
    parses (``parse_adr_number`` / ``_ADR_FILENAME_RE``)."""
    # Capped at 60 (unbounded git-log subject, Windows MAX_PATH risk); the
    # number prefix already guarantees uniqueness so truncation can't collide.
    slug = _ADR_SLUG_STRIP_RE.sub("-", subject.lower()).strip("-")[:60].rstrip("-")
    return slug or "adr"


def _render_adr_spec_md(
    *,
    number: int,
    subject: str,
    status: str,
    date: str,
    commit: str,
    context: str,
    decision: str,
    consequences: str,
    rejected: str = "",
) -> str:
    """Render a standalone spec file; H1 is ``adr_index.read_adr_title``'s parse format."""
    lines = [
        f"# ADR-{number:03d} — {subject}",
        "",
        f"- **Status**: {status}",
        f"- **Date**: {date}",
        f"- **Commit**: `{commit}`",
        "",
        "## Context",
        "",
        context,
        "",
        "## Decision",
        "",
        decision,
        "",
        "## Consequences",
        "",
        consequences,
    ]
    if rejected:
        lines += ["", "## Rejected alternatives", "", rejected]
    lines.append("")
    return "\n".join(lines)


#: 3-digit only, NOT the `\d{3,4}` shared/adr_index.py tolerates — adopt only
#: ever WRITES a 3-digit name, so a 4-digit one (e.g. a year-prefixed
#: `2019-x.md`) can't collide with it; counting it here would only
#: manufacture a false ADR_OUTPUT_MAX_NUMBER overflow (doubt-review, rd 4).
_SEED_FILENAME_NUMBER_RE = re.compile(r"^(\d{3})-")


def _max_seeded_adr_number(project_root: Path) -> int:
    """Highest numeric prefix already seeded in ``ADR_SPEC_FOLDER`` (0 if
    none). Folded into ``_next_adr_start_number`` so a re-run can't reissue
    a number the folder already has. Prevents a NUMBER collision, not
    content duplication — a 2nd successful run still mints a new copy of
    the adoption ADR; accepted, since decision_log.md already duplicated
    the same way (``merge_decision_log`` keeps the prior ADR while
    ``start_adr_number`` advances) — this mirrors pre-existing behavior,
    not a new defect. Re-running past success isn't a documented workflow
    (a retried FAILURE is already a clean no-op, ``write_agent_docs``'s
    fail-closed-first ordering)."""
    folder = project_root / ADR_SPEC_FOLDER
    if not folder.is_dir():
        return 0
    matches = (_SEED_FILENAME_NUMBER_RE.match(p.name) for p in folder.glob("*.md"))
    return max((int(m.group(1)) for m in matches if m), default=0)


def _seed_adr_spec_folder(
    project_root: Path,
    *,
    start_adr_number: int,
    today: str,
    commit_sha: str | None,
    adoption_fields: dict[str, str],
    retroactive_adrs: list[dict[str, Any]],
) -> list[Path]:
    """Seed ``.shipwright/planning/adr/`` with adopt's own minted ADRs — the
    adoption ADR plus any retroactive ADRs (trg-50efc4c8), each through the
    same backup-then-overwrite guardrail as the other ``agent_docs`` artifacts."""
    folder = project_root / ADR_SPEC_FOLDER
    folder.mkdir(parents=True, exist_ok=True)
    commit = commit_sha or "HEAD"
    written: list[Path] = []

    def _write_seed(rel: str, content: str) -> Path:
        path = project_root / rel
        backup = preserve_if_exists(project_root, rel)
        path.write_text(content, encoding="utf-8")
        record_preservation_action(
            project_root,
            file=rel,
            action=("overwritten_with_backup" if backup else "written_fresh"),
            backup_path=backup,
        )
        return path

    adoption_subject = "Adopt this repository into the Shipwright SDLC"
    adoption_rel = f"{ADR_SPEC_FOLDER}/{start_adr_number:03d}-{_adr_slug(adoption_subject)}.md"
    written.append(_write_seed(adoption_rel, _render_adr_spec_md(
        number=start_adr_number, subject=adoption_subject, status="accepted",
        date=today, commit=commit,
        context=adoption_fields["context"], decision=adoption_fields["decision"],
        consequences=adoption_fields["consequences"], rejected=adoption_fields["rejected"],
    )))

    for idx, adr in enumerate(retroactive_adrs, start=start_adr_number + 1):
        subject = adr["subject"]
        rel = f"{ADR_SPEC_FOLDER}/{idx:03d}-{_adr_slug(subject)}.md"
        written.append(_write_seed(rel, _render_adr_spec_md(
            number=idx, subject=subject,
            status="accepted (retroactive, llm-inferred)",
            date=today, commit=(str(adr.get("sha") or "").strip() or "unknown"),
            context=adr["context"], decision=adr["decision"], consequences=adr["consequences"],
        )))

    return written


def _refresh_adr_index(project_root: Path) -> str | None:
    """Best-effort ``.shipwright/planning/adr/INDEX.md`` refresh after
    seeding — via subprocess, not an in-process import: by now
    ``sys.modules['lib']`` is bound to adopt's own ``lib`` package, and
    ``adr_index.py``'s absolute ``lib.*`` imports would collide (ADR-045).
    Returns ``None`` on success, else a warning — never raises, since a
    stale index must not abort an otherwise-successful adoption.
    """
    script = (
        Path(__file__).resolve().parents[4]
        / "shared" / "scripts" / "tools" / "rebuild_adr_index.py"
    )
    if not script.is_file():
        return f"could not refresh {ADR_SPEC_FOLDER}/INDEX.md: {script} not found"
    try:
        result = subprocess.run(
            [sys.executable, str(script), "--project-root", str(project_root)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
            check=False,
        )
    except (subprocess.SubprocessError, OSError) as exc:
        return f"could not refresh {ADR_SPEC_FOLDER}/INDEX.md: {exc}"
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        return (
            f"could not refresh {ADR_SPEC_FOLDER}/INDEX.md: "
            f"exit {result.returncode}: {detail}"
        )
    return None
