"""Generate e2e/flows/adopted-baseline.spec.ts from crawled routes.

Input: routes.json (from Layer-1.5 Playwright crawler).
Output: e2e/flows/adopted-baseline.spec.ts — mechanical regression guard.

The generated tests intentionally avoid semantic assertions (would be
hallucinations). They check: page loads, h1 matches, top CTAs visible,
form inputs present. User refines them after adoption.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:  # tool context: generate_adoption_artifacts puts lib/ on sys.path
    from fr_id_sequence import canonical_fr_id
except ImportError:  # test / package context: scripts/ on sys.path, lib is a package
    from lib.fr_id_sequence import canonical_fr_id


def _escape_ts_string(s: str) -> str:
    """Escape a string for safe embedding in a TypeScript single-quoted literal."""
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").strip()


def _safe_test_name(route: dict[str, Any], fr_id: str) -> str:
    title = route.get("title") or route.get("url", "?")
    clean = re.sub(r"[^\w\s-]", "", str(title))[:60].strip()
    return f"{fr_id} — {route.get('url', '?')} ({clean})"


def _render_one_test(route: dict[str, Any], fr_id: str) -> str:
    url = route.get("url", "/")
    test_name = _safe_test_name(route, fr_id)
    name_esc = _escape_ts_string(test_name)
    url_esc = _escape_ts_string(url)
    h1 = route.get("h1")
    buttons = route.get("buttons") or []
    asserts = [f"  await page.goto('{url_esc}');"]
    asserts.append("  await expect(page).toHaveURL(new RegExp(escapeRegex('"
                   + url_esc + "')));")
    if h1:
        h1_esc = _escape_ts_string(h1)
        asserts.append(f"  await expect(page.locator('h1').first()).toContainText('{h1_esc}');")
    # Visible CTAs (up to 3)
    for btn in buttons[:3]:
        btn_esc = _escape_ts_string(str(btn))
        if btn_esc:
            asserts.append(
                f"  await expect(page.getByRole('button', {{ name: /{re.escape(btn_esc)}/i }}).or("
                f"page.getByText('{btn_esc}'))).toBeVisible();"
            )
    body = "\n".join(asserts)
    return f"""test('{name_esc}', async ({{ page }}) => {{
{body}
}});
"""


def render_baseline_spec(routes: list[dict[str, Any]]) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    tests = "\n".join(
        _render_one_test(route, canonical_fr_id(i + 1)) for i, route in enumerate(routes)
    )
    if not tests:
        tests = "// No routes crawled — baseline suite empty.\n"
    return f"""// Auto-generated by /shipwright-adopt on {today}.
// Purpose: regression guard — fails if basic navigation breaks.
// Refine these tests with real acceptance criteria as features evolve via /shipwright-iterate.

import {{ test, expect }} from '@playwright/test';

function escapeRegex(s: string): string {{
  return s.replace(/[.*+?^${{}}()|[\\]\\\\]/g, '\\\\$&');
}}

{tests}
"""


def write_baseline_spec(project_root: Path, routes: list[dict[str, Any]]) -> Path:
    spec_dir = project_root / "e2e" / "flows"
    spec_dir.mkdir(parents=True, exist_ok=True)
    spec_path = spec_dir / "adopted-baseline.spec.ts"
    spec_path.write_text(render_baseline_spec(routes), encoding="utf-8")
    return spec_path
