"""Render and write the adopted project's planning spec.

Extracted from ``artifact_writer`` for the same reason ``spec_table`` was: that
module is grandfathered at its bloat ceiling, and the spec document grew a
second output — the machine-readable summary of the very table it renders.

Keeping both writes here is deliberate. ``spec.md``'s provenance block and
``.shipwright/adopt/derived-catalogue.json`` are two views of one claim (*these
are the requirements, and nobody has confirmed them*), so they are produced from
a single ``summarize`` pass and written by a single function. A pair like that
derived at two call sites is precisely how a reported count comes to describe a
different table than the one handed over.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from lib.derived_catalogue import (  # noqa: E402
    DerivedCatalogue,
    render_provenance_banner,
    summarize,
)
from lib.derived_catalogue_doc import write_summary  # noqa: E402
from lib.render_helpers import _utc_today  # noqa: E402
from lib.spec_table import render_fr_table  # noqa: E402


def _render_spec_md(
    *,
    project_name: str,
    split_name: str,
    product_description: str,
    features: list[dict[str, Any]],
    qr_items: list[str],
    constraints: list[str],
    catalogue: DerivedCatalogue | None = None,
) -> str:
    today = _utc_today()
    # The table — header, separator and rows — is rendered by `spec_table` in the
    # ONE converged shape (campaign S5). Not inlined here: the header is a shared
    # constant both generators emit, and the cells need Markdown escaping that a
    # bare f-string never applied.
    fr_table = render_fr_table(features, split_name=split_name)
    # …and above it, the block that says the catalogue was DERIVED and nobody has
    # confirmed it (trg-1aa5a8ab). Prose, never a table row: every FR-table
    # consumer is line-based on a leading `|`. `catalogue` is threaded in when the
    # caller already computed it, so the count reported at handover and the count
    # printed here come from one derivation.
    banner = render_provenance_banner(
        catalogue if catalogue is not None
        else summarize(features, split_name=split_name)
    )
    qr_block = ""
    for idx, qr in enumerate(qr_items, start=1):
        qr_block += f"- **QR-{idx:02d}**: {qr}\n"
    if not qr_block:
        qr_block = "_No quality requirements inferred._\n"
    constraint_block = ""
    for idx, c in enumerate(constraints, start=1):
        constraint_block += f"- **C-{idx:02d}**: {c}\n"
    if not constraint_block:
        constraint_block = "_No constraints inferred._\n"

    # Acceptance Criteria block. When any FR carries non-empty
    # `acceptance_criteria`, render a per-FR sub-list with origin marker
    # (enrichment / tests). FRs without ACs keep today's "TBD" placeholder.
    has_any_ac = any(f.get("acceptance_criteria") for f in features)
    ac_block = ""
    if has_any_ac:
        for f in features:
            fr_id = f.get("fr_id", "FR-01.?")
            label = f.get("label", "")
            acs = f.get("acceptance_criteria") or []
            source = f.get("acceptance_source") or ""
            if not acs:
                ac_block += (
                    f"### {fr_id} — {label}\n\n"
                    "_TBD — refine via /shipwright-iterate._\n\n"
                )
                continue
            origin_note = (
                f"_Source: {source}._" if source else ""
            )
            ac_block += f"### {fr_id} — {label}\n\n{origin_note}\n\n"
            for ac in acs:
                ac_block += f"- {ac}\n"
            ac_block += "\n"
    else:
        ac_block = (
            "Acceptance criteria per FR are placeholders (`TBD`) — refine them "
            "with explicit behavior expectations as features evolve via "
            "`/shipwright-iterate`.\n\n"
            "The auto-generated E2E baseline at `e2e/flows/adopted-baseline.spec.ts` "
            "(if Playwright crawl succeeded) covers mechanical rendering / "
            "visibility checks, not semantic behavior.\n"
        )

    return f"""# Specification — {project_name} / {split_name}

_Generated by /shipwright-adopt on {today}. Refine via /shipwright-iterate._

## Abstract

{product_description}

## Functional Requirements

{banner}

{fr_table}

## Quality Requirements

{qr_block}

## Constraints

{constraint_block}

## Acceptance Criteria

{ac_block}"""

def write_spec(
    project_root: Path,
    *,
    project_name: str,
    split_name: str,
    product_description: str,
    features: list[dict[str, Any]],
    qr_items: list[str],
    constraints: list[str],
) -> list[Path]:
    """Write the planning spec **and** the machine-readable summary of it.

    Both, from one ``summarize`` pass, because they are two views of a single
    claim — *these are the requirements, and nobody has confirmed them*. Writing
    them together is what makes it structurally impossible for the count reported
    at handover to describe a different table than the one handed over
    (trg-1aa5a8ab); two call sites deriving it independently is exactly how such
    a pair drifts.

    Returns both paths, spec first.

    There is deliberately **no** caller-supplied catalogue override. One existed
    and was removed: it let a caller hand in a summary derived from different
    features, which would then be written beside a table rendered from these —
    two artifacts disagreeing by construction, which is precisely the drift this
    pairing exists to prevent (external code review).
    """
    catalogue = summarize(features, split_name=split_name)
    split_dir = project_root / ".shipwright" / "planning" / split_name
    split_dir.mkdir(parents=True, exist_ok=True)
    spec = split_dir / "spec.md"
    spec.write_text(_render_spec_md(
        project_name=project_name, split_name=split_name,
        product_description=product_description, features=features,
        qr_items=qr_items, constraints=constraints, catalogue=catalogue,
    ), encoding="utf-8")
    return [spec, write_summary(project_root, catalogue)]


__all__ = ["write_spec"]
