"""Generate adopt's visual frontend documentation (Tier 5).

For projects with a frontend (Vite/React/Next/etc.), produce:
- `.shipwright/agent_docs/design_tokens.md` — colors / spacing / typography / CSS vars
- `.shipwright/agent_docs/guideline.md` — single-page design-system summary, including
  a components inventory and a link to the persisted screenshots
- `.shipwright/agent_docs/visual/screenshots/` — copies of the crawl screenshots from
  `.shipwright/adopt/screenshots/` (which lives in the gitignored adopt
  workdir; adopt's docs need a stable, committed location).

Backend-only projects produce a trivial result with `wrote_docs: false`
and `component_count: 0` — the SKILL.md handoff treats that as "no
visual docs needed for this profile".
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path
from typing import Any

AGENT_DOCS_DIR = ".shipwright/agent_docs"
LEGACY_AGENT_DOCS_DIRNAME = "agent_docs"

# Importable both as `lib.visual_docs_generator` (test path: lib/__init__.py)
# AND as `visual_docs_generator` (production path via `_load_lib()` which
# adds scripts/lib to sys.path and uses absolute names).
sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    from .component_inventory import build_component_inventory  # type: ignore
    from .design_tokens import extract_design_tokens  # type: ignore
except ImportError:
    from component_inventory import build_component_inventory  # type: ignore
    from design_tokens import extract_design_tokens  # type: ignore


def _render_design_tokens_md(tokens: dict[str, Any]) -> str:
    def _table(title: str, items: dict[str, str]) -> str:
        if not items:
            return f"### {title}\n\n_None detected._\n\n"
        rows = "\n".join(f"| `{k}` | `{v}` |" for k, v in sorted(items.items()))
        return f"### {title}\n\n| Token | Value |\n|-------|-------|\n{rows}\n\n"

    return (
        "# Design Tokens\n\n"
        "_Extracted by /shipwright-adopt from tailwind.config.* and `:root` CSS variables._\n\n"
        + _table("Colors", tokens["colors"])
        + _table("Spacing", tokens["spacing"])
        + _table("Typography", tokens["typography"])
        + _table("CSS Variables", tokens["css_vars"])
    )


def _render_guideline_md(
    tokens: dict[str, Any],
    inventory: dict[str, Any],
    screenshots_count: int,
) -> str:
    color_summary = (
        ", ".join(f"`{name}` = `{val}`" for name, val in list(tokens["colors"].items())[:10])
        or "_no Tailwind colors detected — see CSS Variables in design_tokens.md_"
    )
    type_summary = (
        ", ".join(f"`{name}` = `{val}`" for name, val in list(tokens["typography"].items())[:10])
        or "_no typography scale detected_"
    )
    if inventory["total"] == 0:
        components_block = "_No components detected under src/components, src/ui, or src/app._\n"
    else:
        rows = "\n".join(
            f"| `{c['name']}` | `{c['path']}` | {c['props_count']} | {c['usage_count']} |"
            for c in sorted(inventory["components"], key=lambda x: -x["usage_count"])[:50]
        )
        components_block = (
            f"Detected **{inventory['total']}** component(s):\n\n"
            "| Name | Path | Props | Usages |\n"
            "|------|------|-------|--------|\n"
            f"{rows}\n"
        )
    screenshot_block = (
        f"{screenshots_count} screenshot(s) persisted to `{AGENT_DOCS_DIR}/visual/screenshots/`."
        if screenshots_count > 0
        else "_No crawl screenshots available — run /shipwright-adopt with the dev server up to populate._"
    )
    return (
        "# Visual Guideline\n\n"
        "_Auto-generated by /shipwright-adopt. Refine via /shipwright-iterate._\n\n"
        "## Colors\n\n"
        f"{color_summary}\n\n"
        f"_Full token list: `{AGENT_DOCS_DIR}/design_tokens.md`._\n\n"
        "## Typography\n\n"
        f"{type_summary}\n\n"
        "## Components\n\n"
        f"{components_block}\n"
        "## Screenshots\n\n"
        f"{screenshot_block}\n"
    )


def _persist_screenshots(project_root: Path) -> int:
    src_dir = project_root / ".shipwright" / "adopt" / "screenshots"
    dst_dir = project_root / AGENT_DOCS_DIR / "visual" / "screenshots"
    if not src_dir.is_dir():
        return 0
    dst_dir.mkdir(parents=True, exist_ok=True)
    count = 0
    for f in src_dir.iterdir():
        if not f.is_file():
            continue
        if f.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
            continue
        shutil.copy2(f, dst_dir / f.name)
        count += 1
    return count


def generate_visual_docs(
    project_root: Path,
    frontend_root: Path | None = None,
) -> dict[str, Any]:
    """Generate visual docs for the project. Returns a result dict the
    caller can surface in the handoff.

    `frontend_root` defaults to `project_root` for single-service repos.
    For multi-service repos pass the primary frontend service dir
    (e.g. `<project_root>/client`) so component scan + tailwind parse
    look in the right place.
    """
    fe_root = frontend_root or project_root
    inventory = build_component_inventory(fe_root)
    tokens = extract_design_tokens(fe_root)
    screenshots_count = _persist_screenshots(project_root)

    has_visual_signal = (
        inventory["total"] > 0
        or any(tokens[k] for k in ("colors", "spacing", "typography", "css_vars"))
        or screenshots_count > 0
    )

    if not has_visual_signal:
        return {
            "wrote_docs": False,
            "component_count": 0,
            "screenshots_persisted": 0,
            "design_tokens": None,
            "guideline": None,
        }

    agent_docs = project_root / AGENT_DOCS_DIR
    agent_docs.mkdir(parents=True, exist_ok=True)
    design_tokens_path = agent_docs / "design_tokens.md"
    guideline_path = agent_docs / "guideline.md"

    # Preserve hand-edited copies before regenerating. The visual docs ARE
    # auto-generated, but operators may add notes between adopt runs — losing
    # those silently is the same anti-pattern fixed for CLAUDE.md / decision_log.
    # Re-uses the same `<root>/.shipwright/adopt/backups/` location.
    try:
        from preserve_existing import preserve_if_exists, record_preservation_action  # type: ignore
    except ImportError:
        from .preserve_existing import preserve_if_exists, record_preservation_action  # type: ignore

    for rel in (f"{AGENT_DOCS_DIR}/design_tokens.md", f"{AGENT_DOCS_DIR}/guideline.md"):
        backup = preserve_if_exists(project_root, rel)
        if backup is not None:
            record_preservation_action(
                project_root,
                file=rel,
                action="overwritten_with_backup",
                backup_path=backup,
                note="visual docs regenerated by adopt (Tier 5)",
            )

    design_tokens_path.write_text(_render_design_tokens_md(tokens), encoding="utf-8")
    guideline_path.write_text(
        _render_guideline_md(tokens, inventory, screenshots_count),
        encoding="utf-8",
    )

    return {
        "wrote_docs": True,
        "component_count": inventory["total"],
        "screenshots_persisted": screenshots_count,
        "design_tokens": design_tokens_path,
        "guideline": guideline_path,
    }
