"""Tests for filter_generated_paths / is_generated_path in pr_review_lib.py.

Root fix for the Tier-3 truncation false-positive (triage trg-e1c554d9): a
medium+ shipwright PR diff is dominated (~82% of chars, measured on PR #310) by
producer-REGENERATED artifacts — compliance MDs, the three regenerated
agent-docs, changelog drops, append-log state files, and prior review records —
that carry no reviewable logic. Dropping those file-sections from the diff
BEFORE the truncation check keeps the reviewer under MAX_DIFF_CHARS AND focuses
it on real code. Two things are deliberately NOT in that set and are pinned as
such below: dependency lockfiles, and the authored files under
`.shipwright/agent_docs`.
Split into its own test module (kept test_pr_review_lib.py under the
source-size guideline).

The adversarial half — a PR forging a file boundary inside its own diff — lives
in test_pr_review_forged_boundary.py, for the same size reason.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).parent.parent
REPO_ROOT = PLUGIN_ROOT.parent.parent
sys.path.insert(0, str(PLUGIN_ROOT / "scripts" / "lib"))

import pr_review_lib as L  # noqa: E402


def _section(path: str, body: str = "@@ -1 +1 @@\n-old\n+new\n") -> str:
    return f"diff --git a/{path} b/{path}\nindex 111..222 100644\n--- a/{path}\n+++ b/{path}\n{body}"


class TestIsGeneratedPath:
    def test_compliance_prefix(self):
        assert L.is_generated_path(".shipwright/compliance/dashboard.md")

    def test_the_three_regenerated_agent_docs(self):
        for name in ("build_dashboard.md", "session_handoff.md", "triage_inbox.md"):
            assert L.is_generated_path(f".shipwright/agent_docs/{name}"), name
        assert L.is_generated_path(".shipwright/agent_docs/iterates/run-x.json")
        assert L.is_generated_path(".shipwright/agent_docs/runtime/whatever.json")

    def test_authored_agent_docs_are_NOT_generated(self):
        """The directory is this repo's agent-instruction surface.

        A blanket `.shipwright/agent_docs/` prefix hid `architecture.md` (curated
        prose the churn resolver specifically refuses to auto-merge), the
        requirements `spec.md`, and the hand-written conventions / decision log —
        from the one reviewer whose own system prompt orders it to BLOCK on an
        injected instruction in agent markdown. Same error as the lockfile one,
        one prefix earlier. See iterate-2026-07-27-pr-review-forged-boundary.
        """
        for name in ("architecture.md", "spec.md", "conventions.md",
                     "decision_log.md", "known_issues.md", "test_status_overrides.md"):
            assert not L.is_generated_path(f".shipwright/agent_docs/{name}"), name

    def test_the_regenerated_set_matches_the_repo_churn_allowlist(self):
        """Forward drift protection against the SSoT one directory up.

        `shared/scripts/lib/churn_merge.AGENT_DOC_MDS` is the repo's own list of
        regenerated agent-docs. A producer added there and not here would start
        dominating every reviewed diff again; one removed there and left here
        would go silently unreviewed. The plugin cannot import that module
        (ADR-045 lib-collision), so the registry is read as text.
        """
        src = (REPO_ROOT / "shared" / "scripts" / "lib" / "churn_merge.py").read_text(
            encoding="utf-8")
        block = src.split("AGENT_DOC_MDS", 1)[1].split(")", 1)[0]
        names = re.findall(r'"([a-z_]+)"', block)
        assert set(names) == {"build_dashboard", "session_handoff", "triage_inbox"}, names
        for name in names:
            assert L.is_generated_path(f".shipwright/agent_docs/{name}.md"), name

    def test_changelog_drops_prefix(self):
        assert L.is_generated_path("CHANGELOG-unreleased.d/Added/foo_001.md")

    def test_a_lockfile_is_NOT_generated(self):
        """A dependency lockfile is reviewable, and on an untrusted PR it is the
        most reviewable thing in the diff — it is where a substituted or
        typosquatted package arrives, regenerated by whoever opened the PR.
        Filtering it hid every dependency change that shared a PR with one
        ordinary file. See iterate-2026-07-27-pr-review-forged-boundary."""
        for lock in ("uv.lock", "plugins/shipwright-grade/uv.lock", "poetry.lock",
                     "package-lock.json", "Cargo.lock", "yarn.lock", "pnpm-lock.yaml"):
            assert not L.is_generated_path(lock), lock

    def test_state_logs(self):
        assert L.is_generated_path("shipwright_test_results.json")
        assert L.is_generated_path("shipwright_events.jsonl")
        assert L.is_generated_path(".shipwright/triage.jsonl")


class TestReviewEvidenceExcluded:
    """A reviewer must not be fed the transcripts of prior reviews.

    `reviews.json` (record_review_pass) and the `*-external-*review*.json`
    replies (external_review) are tool-written records OF a review. Reviewing
    them is circular, and they are bulky: 45,596 chars — 19% of the reviewed
    diff — on PR #446, which was the difference between fitting the size cap
    and failing closed on truncation.
    """

    RUN = ".shipwright/planning/iterate/iterate-2026-07-27-a-run"

    def test_review_record_is_excluded(self):
        assert L.is_generated_path(f"{self.RUN}/reviews.json")

    def test_raw_external_review_replies_are_excluded(self):
        for name in (
            "iterate-2026-07-27-a-run-external-review.json",
            "iterate-2026-07-27-a-run-external-code-review.json",
            "iterate-2026-07-27-a-run-external-code-review-head.json",
            "iterate-2026-07-27-a-run-external-code-review-final.json",
        ):
            assert L.is_generated_path(
                f".shipwright/planning/iterate/{name}"), name

    def test_the_iterate_spec_and_miniplan_stay_reviewable(self):
        """The narrow half of the rule, and the point of it.

        These are AUTHORED, they state the acceptance criteria, and they are
        the intent a reviewer should read the diff against. Excluding them
        would trade a size win for review quality.
        """
        assert not L.is_generated_path(
            ".shipwright/planning/iterate/iterate-2026-07-27-a-run.md")
        assert not L.is_generated_path(
            ".shipwright/planning/iterate/iterate-2026-07-27-a-run-MINIPLAN.md")

    def test_a_json_elsewhere_under_planning_is_not_excluded(self):
        # The rule is scoped to the iterate run directory, not all planning.
        assert not L.is_generated_path(
            ".shipwright/planning/01-adopted/reviews.json")
        assert not L.is_generated_path("src/reviews.json")

    def test_an_unrelated_json_in_the_run_dir_is_not_excluded(self):
        assert not L.is_generated_path(f"{self.RUN}/result.json")

    def test_the_sections_are_dropped_from_a_real_diff(self):
        diff = (
            _section("plugins/shipwright-test/scripts/lib/thing.py")
            + _section(f"{self.RUN}/reviews.json")
            + _section(".shipwright/planning/iterate/run-external-review.json")
            + _section(".shipwright/planning/iterate/run.md")
        )
        filtered, excluded = L.filter_generated_paths(diff)

        assert "thing.py" in filtered
        assert "run.md" in filtered            # authored intent survives
        assert "reviews.json" not in filtered
        assert "external-review.json" not in filtered
        assert len(excluded) == 2

    def test_real_source_not_generated(self):
        assert not L.is_generated_path("shared/scripts/tools/measure_diff_coverage.py")
        assert not L.is_generated_path("plugins/shipwright-security/scripts/lib/pr_review_lib.py")
        assert not L.is_generated_path(".github/workflows/ci.yml")
        # a hand-authored planning doc / roadmap is source, not generated
        assert not L.is_generated_path(".shipwright/planning/diff-coverage-roadmap.md")


class TestFilterGeneratedPaths:
    def test_drops_generated_keeps_source(self):
        diff = (
            _section("shared/scripts/tools/foo.py")
            + _section(".shipwright/compliance/dashboard.md")
            + _section("triage.jsonl")
            + _section("plugins/x/bar.py")
        )
        filtered, excluded = L.filter_generated_paths(diff)
        assert "shared/scripts/tools/foo.py" in filtered
        assert "plugins/x/bar.py" in filtered
        assert ".shipwright/compliance/dashboard.md" not in filtered
        assert "triage.jsonl" not in filtered
        assert excluded == [".shipwright/compliance/dashboard.md", "triage.jsonl"]

    def test_all_source_unchanged(self):
        diff = _section("a/x.py") + _section("b/y.py")
        filtered, excluded = L.filter_generated_paths(diff)
        assert filtered == diff
        assert excluded == []

    def test_no_headers_returned_unchanged(self):
        # A diff with no `diff --git` headers (unexpected) is passed through.
        diff = "not a diff at all\njust text\n"
        filtered, excluded = L.filter_generated_paths(diff)
        assert filtered == diff
        assert excluded == []

    def test_excluded_is_sorted_and_deduped(self):
        # Two sections touching the SAME generated path must report it once, and
        # the unfiltered lockfile must not appear at all.
        diff = (_section("uv.lock") + _section("triage.jsonl")
                + _section(".shipwright/compliance/x.md") + _section("triage.jsonl"))
        _, excluded = L.filter_generated_paths(diff)
        assert excluded == [".shipwright/compliance/x.md", "triage.jsonl"]

    def test_deleted_generated_file_excluded(self):
        # A deletion has `+++ /dev/null`; path must resolve from the `--- a/` side.
        diff = (
            "diff --git a/triage.jsonl b/triage.jsonl\n"
            "deleted file mode 100644\n"
            "index 111..000\n"
            "--- a/triage.jsonl\n"
            "+++ /dev/null\n"
            "@@ -1 +0,0 @@\n-gone\n"
        ) + _section("keep/me.py")
        filtered, excluded = L.filter_generated_paths(diff)
        assert excluded == ["triage.jsonl"]
        assert "keep/me.py" in filtered

    def test_new_generated_file_excluded(self):
        # An addition has `--- /dev/null`; path resolves from the `+++ b/` side.
        diff = (
            "diff --git a/CHANGELOG-unreleased.d/Added/x_001.md b/CHANGELOG-unreleased.d/Added/x_001.md\n"
            "new file mode 100644\n"
            "index 000..111\n"
            "--- /dev/null\n"
            "+++ b/CHANGELOG-unreleased.d/Added/x_001.md\n"
            "@@ -0,0 +1 @@\n+added\n"
        )
        filtered, excluded = L.filter_generated_paths(diff)
        assert excluded == ["CHANGELOG-unreleased.d/Added/x_001.md"]
        assert filtered.strip() == ""  # everything excluded

    def test_rename_real_source_into_generated_dir_is_kept(self):
        # Codex review SHOULD-FIX: a rename that MOVES real source into a
        # generated dir must NOT be silently dropped — the real code (and the
        # suspicious move itself) must stay reviewable. Exclude only when EVERY
        # touched path is generated.
        diff = (
            "diff --git a/plugins/x/real.py b/.shipwright/compliance/real.py\n"
            "similarity index 100%\n"
            "rename from plugins/x/real.py\n"
            "rename to .shipwright/compliance/real.py\n"
        )
        filtered, excluded = L.filter_generated_paths(diff)
        assert filtered == diff       # kept in full
        assert excluded == []         # real source side wins

    def test_rename_generated_to_generated_still_excluded(self):
        # A rename where BOTH ends are generated carries no reviewable logic.
        diff = (
            "diff --git a/.shipwright/compliance/old.md b/.shipwright/compliance/new.md\n"
            "similarity index 100%\n"
            "rename from .shipwright/compliance/old.md\n"
            "rename to .shipwright/compliance/new.md\n"
        )
        _, excluded = L.filter_generated_paths(diff)
        assert excluded == [".shipwright/compliance/new.md", ".shipwright/compliance/old.md"]

    def test_filtering_lets_a_big_diff_fit_under_cap(self):
        # The whole point: a diff that WOULD truncate fits once generated noise
        # is dropped, so the review runs instead of failing closed.
        # The fixture is sized FROM the cap: hard-coding a line count silently
        # stops exercising the over-cap path the day the cap is raised.
        filler = "+x\n" * ((L.MAX_DIFF_CHARS // 3) + 1_000)
        big_generated = _section(
            ".shipwright/compliance/test-evidence.md", body="@@ -1 +1 @@\n" + filler)
        small_source = _section("shared/real.py")
        diff = big_generated + small_source
        assert len(diff) > L.MAX_DIFF_CHARS
        filtered, excluded = L.filter_generated_paths(diff)
        assert len(filtered) < L.MAX_DIFF_CHARS
        assert L.truncate_diff(filtered).incomplete is False
        assert excluded == [".shipwright/compliance/test-evidence.md"]
