#!/usr/bin/env python3
"""Screen registry for shipwright-design.

Tracks generated screens, user flows, and uploaded assets.
Reads/writes ``.shipwright/designs/design-manifest.md`` (caller passes
the canonical directory; this module is parameter-driven).

Usage:
    uv run screen_registry.py list --designs-dir <path>
    uv run screen_registry.py add --designs-dir <path> --name <name> --type <screen|flow|upload> --file <path> --frs <FR-01.01,FR-01.02>
"""

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ScreenEntry:
    number: int
    name: str
    file: str
    status: str = "pending"
    linked_frs: list[str] = field(default_factory=list)
    entry_type: str = "screen"  # screen, flow, upload


def scan_designs_dir(designs_dir: Path) -> dict:
    """Scan a designs directory (canonical: ``.shipwright/designs``) and return inventory."""
    result = {"screens": [], "flows": [], "uploads": []}

    screens_dir = designs_dir / "screens"
    if screens_dir.is_dir():
        for f in sorted(screens_dir.iterdir()):
            if f.suffix == ".html":
                match = re.match(r"^(\d{2})-(.+)\.html$", f.name)
                if match:
                    result["screens"].append({
                        "number": int(match.group(1)),
                        "name": match.group(2),
                        "file": f"screens/{f.name}",
                        "status": "complete",
                    })

    flows_dir = designs_dir / "flows"
    if flows_dir.is_dir():
        for f in sorted(flows_dir.iterdir()):
            if f.suffix == ".html":
                result["flows"].append({
                    "name": f.stem,
                    "file": f"flows/{f.name}",
                    "status": "complete",
                })

    uploads_dir = designs_dir / "uploads"
    if uploads_dir.is_dir():
        for f in sorted(uploads_dir.iterdir()):
            if f.suffix in (".html", ".png", ".jpg", ".jpeg", ".svg", ".pdf", ".md"):
                entry = {
                    "name": f.name,
                    "file": f"uploads/{f.name}",
                    "type": f.suffix[1:],
                    "integrated": False,
                }
                # Detect visual guidelines
                if f.suffix == ".md":
                    content = f.read_text(encoding="utf-8").lower()
                    if "visual guideline" in content or "design token" in content or "color system" in content:
                        entry["is_visual_guidelines"] = True
                result["uploads"].append(entry)

    # Check for generated visual guidelines
    guidelines_path = designs_dir / "visual-guidelines.md"
    result["has_visual_guidelines"] = guidelines_path.exists()
    if guidelines_path.exists():
        result["visual_guidelines_path"] = "visual-guidelines.md"

    return result


def generate_manifest(designs_dir: Path, project_name: str = "", profile_name: str = "") -> str:
    """Generate design-manifest.md content from directory scan."""
    inventory = scan_designs_dir(designs_dir)

    lines = [
        "# Design Manifest",
        "",
        f"> Generated by shipwright-design | Profile: {profile_name}",
        "",
    ]

    # Screens
    lines.append("## Screens")
    lines.append("")
    if inventory["screens"]:
        lines.append("| # | Screen | File | Status | Linked FRs |")
        lines.append("|---|--------|------|--------|-----------|")
        for s in inventory["screens"]:
            frs = s.get("linked_frs", "")
            lines.append(f"| {s['number']:02d} | {s['name']} | {s['file']} | {s['status']} | {frs} |")
    else:
        lines.append("No screens generated yet.")
    lines.append("")

    # Flows
    lines.append("## User Flows")
    lines.append("")
    if inventory["flows"]:
        lines.append("| Flow | File | Status |")
        lines.append("|------|------|--------|")
        for f in inventory["flows"]:
            lines.append(f"| {f['name']} | {f['file']} | {f['status']} |")
    else:
        lines.append("No user flows generated yet.")
    lines.append("")

    # Uploads
    if inventory["uploads"]:
        lines.append("## Uploads")
        lines.append("")
        lines.append("| File | Type | Integrated |")
        lines.append("|------|------|-----------|")
        for u in inventory["uploads"]:
            lines.append(f"| {u['name']} | {u['type']} | {'yes' if u['integrated'] else 'no'} |")
        lines.append("")

    return "\n".join(lines)


def write_manifest(designs_dir: Path, project_name: str = "", profile_name: str = "") -> Path:
    """Write design-manifest.md to the designs directory."""
    content = generate_manifest(designs_dir, project_name, profile_name)
    manifest_path = designs_dir / "design-manifest.md"
    manifest_path.write_text(content, encoding="utf-8")
    return manifest_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Screen registry")
    subparsers = parser.add_subparsers(dest="command", required=True)

    p = subparsers.add_parser("list")
    p.add_argument("--designs-dir", required=True)

    p = subparsers.add_parser("write-manifest")
    p.add_argument("--designs-dir", required=True)
    p.add_argument("--project-name", default="")
    p.add_argument("--profile-name", default="")

    args = parser.parse_args()
    designs_dir = Path(args.designs_dir).resolve()

    if args.command == "list":
        result = scan_designs_dir(designs_dir)
        print(json.dumps(result, indent=2))

    elif args.command == "write-manifest":
        path = write_manifest(designs_dir, args.project_name, args.profile_name)
        print(json.dumps({
            "success": True,
            "path": str(path),
            "inventory": scan_designs_dir(designs_dir),
        }, indent=2))

    return 0


if __name__ == "__main__":
    sys.exit(main())
