#!/usr/bin/env python3
"""Visual comparison: screenshot mockup HTMLs vs live app, generate side-by-side report.

Usage:
    uv run visual_compare.py --cwd <project_root> [--base-url http://localhost:3000]

Reads designs/screen-routes.json for mockup-to-route mapping.
Outputs designs/visual-comparison/index.html with side-by-side pairs.
Returns JSON with comparison results.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def _screenshot_page(url: str, output_path: Path, *, width: int = 1440, height: int = 900, cwd: Path | None = None) -> bool:
    """Take a full-page screenshot via Node.js Playwright (npx)."""
    js_code = f"""
const {{ chromium }} = require('playwright');
(async () => {{
    const browser = await chromium.launch();
    const page = await browser.newPage({{ viewport: {{ width: {width}, height: {height} }} }});
    await page.goto('{url}', {{ waitUntil: 'networkidle', timeout: 15000 }});
    await page.screenshot({{ path: '{output_path.as_posix()}', fullPage: true }});
    await browser.close();
}})().catch(e => {{ console.error(e.message); process.exit(1); }});
"""
    try:
        result = subprocess.run(
            ["node", "-e", js_code],
            capture_output=True,
            timeout=30,
            text=True,
            cwd=str(cwd) if cwd else None,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, OSError):
        return False


def _generate_comparison_html(comparisons: list[dict], output_dir: Path) -> Path:
    """Generate an HTML page showing mockup vs live screenshots side by side."""
    rows = []
    for comp in comparisons:
        mockup_img = comp.get("mockup_screenshot", "")
        live_img = comp.get("live_screenshot", "")
        route = comp.get("route", "")
        mockup_name = comp.get("mockup", "")
        status = "MATCH" if comp.get("match") else "DIFFERS"
        status_color = "#059669" if comp.get("match") else "#DC2626"

        # Use relative paths from output dir
        mockup_rel = Path(mockup_img).name if mockup_img else ""
        live_rel = Path(live_img).name if live_img else ""

        rows.append(f"""
        <div class="comparison">
            <h2>{mockup_name} &rarr; <code>{route}</code>
                <span style="color:{status_color}; font-size:14px; margin-left:12px;">{status}</span>
            </h2>
            <div class="pair">
                <div class="side">
                    <h3>Mockup (Design)</h3>
                    <img src="{mockup_rel}" alt="Mockup: {mockup_name}" />
                </div>
                <div class="side">
                    <h3>Live App</h3>
                    <img src="{live_rel}" alt="Live: {route}" />
                </div>
            </div>
        </div>
        """)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Visual Comparison — Mockup vs Live</title>
<style>
    body {{ font-family: Inter, system-ui, sans-serif; margin: 0; padding: 24px; background: #f5f0eb; color: #1a1a1a; }}
    h1 {{ font-size: 24px; margin-bottom: 8px; }}
    .meta {{ color: #6b7280; font-size: 14px; margin-bottom: 32px; }}
    .comparison {{ background: #fff; border-radius: 12px; padding: 24px; margin-bottom: 24px; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }}
    .comparison h2 {{ font-size: 18px; margin: 0 0 16px 0; }}
    .pair {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }}
    .side h3 {{ font-size: 14px; color: #6b7280; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px; }}
    .side img {{ width: 100%; border: 1px solid #e0dbd4; border-radius: 8px; }}
    code {{ background: #ede8e1; padding: 2px 6px; border-radius: 4px; font-size: 14px; }}
</style>
</head>
<body>
<h1>Visual Comparison</h1>
<p class="meta">{len(comparisons)} screens compared | Generated by shipwright-test --visual</p>
{"".join(rows)}
</body>
</html>"""

    output_path = output_dir / "index.html"
    output_path.write_text(html, encoding="utf-8")
    return output_path


def run_visual_comparison(project_root: Path, base_url: str = "http://localhost:3000") -> dict:
    """Run visual comparison and return results.

    Returns:
        {
            "passed": int,
            "total": int,
            "skipped": bool,
            "skip_reason": str,
            "comparisons": [
                {"mockup": "01-login.html", "route": "/login", "match": True/False,
                 "mockup_screenshot": "path", "live_screenshot": "path"}
            ],
            "report_path": str
        }
    """
    routes_path = project_root / "designs" / "screen-routes.json"
    if not routes_path.exists():
        return {
            "passed": 0,
            "total": 0,
            "skipped": True,
            "skip_reason": "No designs/screen-routes.json found",
            "comparisons": [],
            "report_path": "",
        }

    try:
        routes = json.loads(routes_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        return {
            "passed": 0,
            "total": 0,
            "skipped": True,
            "skip_reason": f"Failed to read screen-routes.json: {e}",
            "comparisons": [],
            "report_path": "",
        }

    if not routes:
        return {
            "passed": 0,
            "total": 0,
            "skipped": True,
            "skip_reason": "screen-routes.json is empty",
            "comparisons": [],
            "report_path": "",
        }

    # Create output directory
    output_dir = project_root / "designs" / "visual-comparison"
    output_dir.mkdir(parents=True, exist_ok=True)

    comparisons = []
    passed = 0
    total = 0

    for mockup_file, route in routes.items():
        total += 1
        mockup_path = project_root / "designs" / "screens" / mockup_file

        if not mockup_path.exists():
            comparisons.append({
                "mockup": mockup_file,
                "route": route,
                "match": False,
                "error": f"Mockup file not found: {mockup_file}",
            })
            continue

        # Screenshot mockup HTML
        mockup_screenshot = output_dir / f"mockup-{mockup_file.replace('.html', '.png')}"
        mockup_url = mockup_path.as_uri()
        mockup_ok = _screenshot_page(mockup_url, mockup_screenshot, cwd=project_root)

        # Screenshot live app
        live_screenshot = output_dir / f"live-{mockup_file.replace('.html', '.png')}"
        live_url = f"{base_url}{route}"
        live_ok = _screenshot_page(live_url, live_screenshot, cwd=project_root)

        # For now, "match" means both screenshots were taken successfully
        # Future: pixel-diff comparison or structural comparison
        match = mockup_ok and live_ok
        if match:
            passed += 1

        comparisons.append({
            "mockup": mockup_file,
            "route": route,
            "match": match,
            "mockup_screenshot": str(mockup_screenshot) if mockup_ok else "",
            "live_screenshot": str(live_screenshot) if live_ok else "",
        })

    # Generate comparison HTML
    report_path = _generate_comparison_html(comparisons, output_dir)

    return {
        "passed": passed,
        "total": total,
        "skipped": False,
        "skip_reason": "",
        "comparisons": comparisons,
        "report_path": str(report_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Visual comparison: mockup vs live")
    parser.add_argument("--cwd", required=True, help="Project root directory")
    parser.add_argument("--base-url", default="http://localhost:3000", help="Live app base URL")
    args = parser.parse_args()

    result = run_visual_comparison(Path(args.cwd).resolve(), args.base_url)
    print(json.dumps(result, indent=2))
    return 0 if not result.get("skipped") else 0


if __name__ == "__main__":
    sys.exit(main())
