"""F11 `session_handoff.md fresh` — decided by CONTENT, never by mtime.

Before iterate-2026-07-27-name-the-blocker this check compared the file's
filesystem mtime against a 600s budget. That fired on any run that spent more
than ten minutes waiting on CI — structurally, not on a defect — and it
contradicted a decision this repo had already recorded and acted on elsewhere
(iterate-2026-06-28-drop-timestamp-drift, standing comment at
``shared/scripts/hooks/check_drift.py:10``): filesystem mtime is not a
content-staleness signal in a git repo, because checkout, branch-switch and
worktree creation all reset it.

The question the check actually wants answered is "does this handoff describe
the run that is finishing right now", and the handoff answers it directly: the
canon frontmatter names the run that generated it. A warning operators learn to
ignore is worse than no warning.
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts"))
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts" / "tools"))

from verifiers.handoff_freshness import (  # noqa: E402
    check_session_handoff_fresh,
    progress_run_id,
)

RUN = "iterate-2026-07-27-name-the-blocker"
OTHER = "iterate-2026-07-01-something-else"


def _write(root: Path, body: str) -> Path:
    docs = root / ".shipwright" / "agent_docs"
    docs.mkdir(parents=True, exist_ok=True)
    path = docs / "session_handoff.md"
    path.write_text(body, encoding="utf-8")
    return path


def _canon(run_id: str, body: str = "") -> str:
    return (
        f'---\ncanon_generated: true\nrun_id: "{run_id}"\nphase: "iterate"\n'
        f'reason: "finalize"\ntimestamp: "2026-07-27T09:00:00+00:00"\n---\n\n'
        f"# Session Handoff\n{body}"
    )


def _progress_block(run_id: str) -> str:
    return (
        "\n## Current Iterate Progress\n\n"
        "- **Branch**: iterate/x\n"
        f"- **Run ID**: {run_id}\n"
    )


# --- the defect this replaces -------------------------------------------------

def test_an_old_file_naming_this_run_passes(tmp_path):
    """The regression. A handoff written 3 hours ago still describes THIS run —
    time spent waiting on CI is not staleness."""
    path = _write(tmp_path, _canon(RUN))
    old = time.time() - 3 * 60 * 60
    os.utime(path, (old, old))

    result = check_session_handoff_fresh(tmp_path, RUN)

    assert result.ok is True
    assert "mtime" not in result.detail.lower()


def test_a_brand_new_file_naming_another_run_fails(tmp_path):
    """The mirror. Freshly written is not the same as about this run — a
    worktree checkout resets mtime on a handoff belonging to someone else."""
    _write(tmp_path, _canon(OTHER))

    result = check_session_handoff_fresh(tmp_path, RUN)

    assert result.ok is False
    assert OTHER in result.detail  # names the run it DOES describe


def test_the_check_never_consults_mtime(tmp_path):
    """Drift guard: the whole point is that the mtime path is deleted, not
    merely out-ranked. Two files identical in content but hours apart in mtime
    must produce identical verdicts."""
    fresh_root = tmp_path / "fresh"
    stale_root = tmp_path / "stale"
    for root in (fresh_root, stale_root):
        root.mkdir()
        _write(root, _canon(RUN))
    old = time.time() - 86_400
    os.utime(stale_root / ".shipwright" / "agent_docs" / "session_handoff.md", (old, old))

    a = check_session_handoff_fresh(fresh_root, RUN)
    b = check_session_handoff_fresh(stale_root, RUN)

    assert (a.ok, a.detail) == (b.ok, b.detail)


# --- content resolution -------------------------------------------------------

def test_body_marker_is_the_fallback_when_no_frontmatter(tmp_path):
    _write(tmp_path, "# Session Handoff\n" + _progress_block(RUN))
    assert check_session_handoff_fresh(tmp_path, RUN).ok is True


def test_last_iterate_run_id_does_not_satisfy_the_check(tmp_path):
    """A handoff carries TWO ``- **Run ID**:`` lines: the previous finalized run
    under ``## Last Iterate``, and the in-flight one under ``## Current Iterate
    Progress``. Matching the first would pass a handoff generated by the run
    BEFORE this one — the exact false pass a substring search would allow."""
    body = (
        "# Session Handoff\n\n## Last Iterate\n\n"
        f"- **Run ID**: {RUN}\n"
        + _progress_block(OTHER)
    )
    _write(tmp_path, body)

    result = check_session_handoff_fresh(tmp_path, RUN)

    assert result.ok is False


def test_run_id_mentioned_only_in_prose_does_not_satisfy_the_check(tmp_path):
    _write(tmp_path, f"# Session Handoff\n\nSee the notes for {RUN} elsewhere.\n")
    assert check_session_handoff_fresh(tmp_path, RUN).ok is False


def test_frontmatter_outranks_the_body_marker(tmp_path):
    """The frontmatter records which run GENERATED the file — the question the
    check asks. The progress block describes the branch and may lag."""
    _write(tmp_path, _canon(RUN, _progress_block(OTHER)))
    assert check_session_handoff_fresh(tmp_path, RUN).ok is True


# --- honest degradation -------------------------------------------------------

def test_missing_file_is_a_warning(tmp_path):
    result = check_session_handoff_fresh(tmp_path, RUN)
    assert result.ok is False
    assert "missing" in result.detail


def test_no_run_id_is_visible_not_a_silent_skip(tmp_path):
    """A caller that supplies no run id must not quietly turn the check off —
    it has to say it could not evaluate."""
    _write(tmp_path, _canon(RUN))

    result = check_session_handoff_fresh(tmp_path, "")

    assert result.ok is False
    assert "no run id" in result.detail.lower()


def test_unreadable_handoff_is_a_warning_not_a_crash(tmp_path):
    docs = tmp_path / ".shipwright" / "agent_docs"
    docs.mkdir(parents=True)
    (docs / "session_handoff.md").mkdir()  # a directory where a file is expected

    result = check_session_handoff_fresh(tmp_path, RUN)

    assert result.ok is False
    # `ok is False` alone would also pass for "missing", and the two have
    # different remedies — write the note vs. fix the path. The reader keeps
    # them apart (`handoff_marker.Handoff.missing`); assert the detail does too.
    assert "unreadable" in result.detail
    assert "missing" not in result.detail


def test_severity_stays_warning(tmp_path):
    """The handoff is advisory, not load-bearing — this check must never become
    the thing that blocks a finalization."""
    _write(tmp_path, _canon(OTHER))
    assert check_session_handoff_fresh(tmp_path, RUN).severity == "warning"


# --- the body-marker parser ---------------------------------------------------

def test_progress_run_id_reads_only_the_progress_section():
    content = (
        "## Last Iterate\n\n- **Run ID**: old-run\n"
        "\n## Current Iterate Progress\n\n- **Run ID**: new-run\n"
        "\n## Git State\n\n- **Run ID**: bogus\n"
    )
    assert progress_run_id(content) == "new-run"


def test_progress_run_id_is_empty_when_the_section_is_absent():
    assert progress_run_id("## Last Iterate\n\n- **Run ID**: old-run\n") == ""
