"""END-TO-END composition test for the handoff freshness contract
(iterate-2026-07-27-name-the-blocker).

Three components share one fact — *which run generated this handoff* — and each
was previously proven only in isolation:

  - **the writer**, ``tools/generate_session_handoff.py``, stamps the canon
    frontmatter (``--canon-marker``, run id read from ``SHIPWRIGHT_RUN_ID``);
  - **the Stop hook**, ``hooks/generate_handoff_on_stop.py``, reads that marker to
    decide it must NOT regenerate and clobber a canon handoff;
  - **the F11 verifier**, ``verifiers/handoff_freshness.py``, reads the same
    marker to decide the handoff describes the run now finishing.

Unit tests pin each side against a *hand-written* frontmatter fixture, which is
exactly the shape of blind spot that lets the three drift apart: all three could
pass their own suites while agreeing on nothing. This proves the real writer's
real output satisfies the real hook and the real verifier, on disk, for the same
run id — and, in the negative direction, that a handoff belonging to a DIFFERENT
run is rejected by both readers together.

Required as integration coverage for the ``cross_component`` risk flag: this
change edits ``hooks/generate_handoff_on_stop.py``, which the F11 verifier
recomputes as cross-component machinery from the diff.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts"))
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts" / "tools"))
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts" / "hooks"))

import generate_handoff_on_stop as stop_hook  # noqa: E402
import generate_session_handoff as writer  # noqa: E402

from verifiers.handoff_freshness import check_session_handoff_fresh  # noqa: E402

RUN = "iterate-2026-07-27-name-the-blocker"
OTHER_RUN = "iterate-2026-07-01-a-different-run"

_HANDOFF_REL = Path(".shipwright") / "agent_docs" / "session_handoff.md"


def _project(tmp_path: Path) -> Path:
    """A minimally-shaped Shipwright project the writer will accept."""
    root = tmp_path / "proj"
    (root / ".shipwright" / "agent_docs").mkdir(parents=True)
    (root / "shipwright_run_config.json").write_text(
        '{"status": "complete", "pipeline": [], "completed_steps": []}', encoding="utf-8"
    )
    return root


def _write_real_handoff(root: Path, run_id: str, phase: str = "iterate") -> Path:
    """Generate the handoff through the REAL writer, with a real canon marker."""
    content = writer.generate_handoff(
        root,
        session_id="sess-1",
        reason="finalize",
        canon_frontmatter={
            "run_id": run_id,
            "phase": phase,
            "reason": "finalize",
            "timestamp": "2026-07-27T09:00:00+00:00",
        },
    )
    path = root / _HANDOFF_REL
    path.write_text(content, encoding="utf-8")
    return path


def test_the_writers_marker_is_the_one_the_verifier_accepts(tmp_path):
    """The forward direction: real writer output → verifier passes."""
    root = _project(tmp_path)
    _write_real_handoff(root, RUN)

    result = check_session_handoff_fresh(root, RUN)

    assert result.ok is True, result.detail


def test_the_writers_marker_is_the_one_the_hook_skips_on(tmp_path, monkeypatch):
    """The same marker, read by the OTHER consumer. If the writer's format and
    the hook's parser ever disagree, the hook silently overwrites the canon
    handoff and the verifier then fails on a file nobody edited."""
    root = _project(tmp_path)
    path = _write_real_handoff(root, RUN)
    monkeypatch.setenv("SHIPWRIGHT_RUN_ID", RUN)

    skip, reason = stop_hook._should_skip_regeneration(path)

    assert skip is True, reason
    assert RUN in reason


def test_hook_and_verifier_agree_when_the_handoff_belongs_to_another_run(tmp_path, monkeypatch):
    """The negative direction, and the one that matters operationally: a handoff
    left behind by a previous run must be regenerated by the hook AND rejected by
    the verifier. Disagreement here is how a stale handoff survives a run."""
    root = _project(tmp_path)
    path = _write_real_handoff(root, OTHER_RUN)
    monkeypatch.setenv("SHIPWRIGHT_RUN_ID", RUN)

    skip, _ = stop_hook._should_skip_regeneration(path)
    verdict = check_session_handoff_fresh(root, RUN)

    assert skip is False          # hook: regenerate it
    assert verdict.ok is False    # verifier: does not describe this run
    assert OTHER_RUN in verdict.detail


def test_both_readers_use_the_same_parser_object(tmp_path):
    """Structural guard behind the two behavioural tests above: one parser, not
    two implementations that happen to agree today."""
    from lib.canon_frontmatter import parse_canon_frontmatter

    assert stop_hook._parse_canon_frontmatter is parse_canon_frontmatter


# --- C3, through its real production path -------------------------------------
#
# iterate-2026-07-27-c3-phase-content-key. C3 has a THIRD consumer of the same
# marker: the Stop-hook phase-quality canon runner. The unit suite proves the
# check; these prove the runner reaches it with a real run id and a real
# writer's file — the join openai R1 of the plan review asked for, rather than
# a direct call with hand-aligned values.


def _c3(findings: list[dict]) -> dict:
    return next(f for f in findings if f["id"] == "C3")


def test_the_canon_runner_passes_c3_on_the_real_writers_marker(tmp_path):
    """Writer → disk → the runner the Stop hook actually calls."""
    from lib.phase_quality import run_canon_checks

    root = _project(tmp_path)
    _write_real_handoff(root, RUN, phase="build")

    finding = _c3(run_canon_checks("build", root, RUN))

    assert finding["status"] == "PASS", finding["evidence"]
    assert RUN in finding["evidence"]


def test_the_canon_runner_warns_when_the_handoff_belongs_to_another_run(tmp_path):
    from lib.phase_quality import run_canon_checks

    root = _project(tmp_path)
    _write_real_handoff(root, OTHER_RUN, phase="build")

    finding = _c3(run_canon_checks("build", root, RUN))

    assert finding["status"] == "WARN"
    assert OTHER_RUN in finding["evidence"]


def test_the_canon_runner_skips_c3_for_a_phase_with_no_producer(tmp_path):
    """`security` is audited by the Stop hook but writes no canon marker. Without
    the applicability set this is where a content key would warn forever."""
    from lib.phase_quality import run_canon_checks

    root = _project(tmp_path)
    _write_real_handoff(root, RUN, phase="build")

    finding = _c3(run_canon_checks("security", root, RUN))

    assert finding["status"] == "SKIP"


def test_a_degenerate_run_id_reaches_c3_as_itself(tmp_path):
    """The runner must not synthesize a run id to fill the gap — an audit with no
    resolvable run has to read as unanswerable, not as a stale handoff."""
    from lib.phase_quality import run_canon_checks

    root = _project(tmp_path)
    _write_real_handoff(root, RUN, phase="build")

    finding = _c3(run_canon_checks("build", root, "unknown"))

    assert finding["status"] == "WARN"
    assert "cannot evaluate" in finding["evidence"]


def test_the_stop_hook_call_site_supplies_the_run_id():
    """Drift guard on the join itself: `run_canon_checks` defaults `run_id` to ""
    so the Stop hook keeps working if this argument is ever dropped — which would
    silently turn every C3 into "cannot evaluate". Pin the production call."""
    import inspect

    import audit_phase_quality_on_stop as audit

    src = inspect.getsource(audit)

    assert "run_canon_checks(phase, project_root, run_id)" in src


def test_hook_runs_from_an_unrelated_working_directory(tmp_path):
    """The extraction moved the parser to ``lib.canon_frontmatter``, so the hook
    now depends on its own sys.path bootstrap resolving. Hooks are launched by
    Claude Code from whatever directory the session happens to be in — an import
    that only resolves when cwd is the repo would fail in production and pass in
    the test suite. Run the real entry point from somewhere else entirely.
    """
    hook_path = REPO_ROOT / "shared" / "scripts" / "hooks" / "generate_handoff_on_stop.py"
    elsewhere = tmp_path / "unrelated"
    elsewhere.mkdir()

    proc = subprocess.run(
        [sys.executable, str(hook_path)],
        cwd=str(elsewhere),
        input="{}",
        capture_output=True,
        text=True,
        timeout=120,
    )

    # The hook is non-blocking by contract (always exit 0) and must not have
    # died on an ImportError before reaching that contract.
    assert proc.returncode == 0, proc.stderr
    assert "ModuleNotFoundError" not in proc.stderr
    assert "canon_frontmatter" not in proc.stderr
