"""The run's handover note must survive its own finalization (P2.15, trg-01cd6aef).

``finalize_iterate._generate_handoff`` (F5b) stamps ``session_handoff.md`` with a canon
marker naming the run that is finishing. F6 correctly does not commit it — it is a
:data:`~lib.derived_snapshots.DERIVED_SNAPSHOTS` path. Then F11's ``ensure_current``
integrates ``main``, ``integrate_main`` calls ``restore_derived_to_head``, and the note
is reset to ``HEAD`` — which on a branch that carries no handoff commit means *some
earlier run's* note.

Nothing downstream puts the marker back. F11's refresh runs
``--preserve-canon-marker``, which carries forward whatever is on disk *"of ANY age …
unchanged"* (``lib/canon_frontmatter.carry_forward_marker``) — mainline's marker. Both
readers then report a staleness the run inflicted on itself:

* ``check_session_handoff_fresh`` (F11) — *"handoff was generated by <other>, not <this>"*;
* ``check_c3_session_handoff_fresh_after_phase`` (Canon C3, every Stop) — *"the note is
  from an earlier iterate run"*.

The premise the restore rests on — *"everything a producer can RE-DERIVE"* — is false for
this one path. The note's BODY is re-derivable; its canon marker is **run identity**, and
identity is not a derivation. Same defect class as ``trg-ad29a709`` (the F5 ledger), one
file over, so it takes the same answer: carry the bytes, do not reset them.

Why the fix is not "drop the F11 check": C3 reads the same bytes on a more frequent
schedule and fails identically, which :func:`test_canon_c3_also_reads_the_destroyed_marker`
pins so a future silencing of one cannot look like a cure.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts"))
sys.path.insert(0, str(REPO_ROOT / "shared" / "scripts" / "tools"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _c3_fixtures import write_handoff, write_iterate_entry  # noqa: E402
from lib.churn_merge import DERIVED_MDS  # noqa: E402
from lib.derived_snapshots import (  # noqa: E402
    DERIVED_SNAPSHOTS,
    SESSION_HANDOFF,
    restore_derived_to_head,
)
from verifiers.handoff_freshness import check_session_handoff_fresh  # noqa: E402
from verifiers.handoff_phase_canon import (  # noqa: E402
    check_c3_session_handoff_fresh_after_phase,
)

THIS_RUN = "iterate-2026-08-05-p2-15-handoff-freshness"
PREV_RUN = "iterate-2026-07-28-some-earlier-run"
THIS_AT = "2026-08-05T12:00:00+00:00"
PREV_AT = "2026-07-28T12:00:00+00:00"


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True, text=True, encoding="utf-8", check=True,
    )


def _write_note(root: Path, run_id: str, at: str) -> None:
    """The note and its completion record, through the SHARED C3 builders.

    Deliberately not hand-rolled. ``_c3_fixtures`` exists because the shape of these
    two artifacts is load-bearing rather than incidental — its ``write_iterate_entry``
    carries every field ``validate_iterate_entry`` requires (``branch``,
    ``tests_passed``), which a local fixture silently omits, and it stamps the wall
    clock 900ms LATER than the anchor on purpose, so a suite built on it cannot return
    the same verdict whether the code read the anchor or the wall clock. A private copy
    here would have been an entry the real writer refuses, asserted against by tests
    that pass anyway (Stage-2 code review, medium).
    """
    write_handoff(root, phase="iterate", run_id=run_id, timestamp=at)
    write_iterate_entry(root, run_id, at)


@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    """A branch whose ``HEAD`` carries a PREVIOUS run's note — the real shape.

    Since iterate-2026-07-27-derived-snapshots-off-branch no iterate commits the note,
    so the committed copy is whatever last touched it (on this repo, #493 on 2026-07-28)
    and every worktree starts from that.
    """
    root = tmp_path / "repo"
    root.mkdir()
    _git(root, "init", "-b", "main")
    _git(root, "config", "user.email", "t@example.com")
    _git(root, "config", "user.name", "t")
    _write_note(root, PREV_RUN, PREV_AT)
    _git(root, "add", "-A")
    _git(root, "commit", "-m", "base")
    return root


def _stamp_this_run(root: Path) -> None:
    """What F5b does: write the note for the run that is finishing, and record it."""
    _write_note(root, THIS_RUN, THIS_AT)


def test_the_registry_path_is_the_one_the_churn_registry_knows() -> None:
    """Forward drift: the constant must resolve into the registry that owns the set.

    The literal lives in ``derived_snapshots`` rather than ``churn_merge`` — the natural
    registry home — because that module sits at exactly the 300-line source limit its own
    docstring says it was split out to respect. This assertion is what buys that: a
    rename in ``churn_merge`` fails here loudly instead of silently emptying the
    carve-out. (The reverse direction is the exact set-difference pin in
    ``test_derived_snapshots_run_written.py``.)
    """
    assert SESSION_HANDOFF in DERIVED_MDS
    assert SESSION_HANDOFF in DERIVED_SNAPSHOTS


def test_the_f11_freshness_check_survives_a_restore(repo: Path) -> None:
    """The reported defect, end to end on one file.

    Green *before* the restore and red after is the whole point: the note was correct,
    and the run's own hygiene step is what made it wrong.
    """
    _stamp_this_run(repo)
    assert check_session_handoff_fresh(repo, THIS_RUN).ok is True, (
        "fixture is wrong: F5b's own write must satisfy the check"
    )

    restore_derived_to_head(repo)

    result = check_session_handoff_fresh(repo, THIS_RUN)
    assert result.ok is True, (
        f"the run's canon marker was reset to HEAD — {result.detail}. This is P2.15: "
        "the marker is run identity, not a derivation, so nothing downstream puts it back"
    )


def test_canon_c3_also_reads_the_destroyed_marker(repo: Path) -> None:
    """The second reader, on the more frequent schedule.

    Pinned so that silencing the F11 check alone can never be mistaken for a fix: C3 asks
    the same question of the same bytes on every Stop, and would have gone on failing.
    """
    _stamp_this_run(repo)
    assert check_c3_session_handoff_fresh_after_phase(repo, "iterate").ok is True

    restore_derived_to_head(repo)

    result = check_c3_session_handoff_fresh_after_phase(repo, "iterate")
    assert result.ok is True, f"Canon C3 reads the same destroyed marker — {result.detail}"


def test_a_staged_handoff_also_survives(repo: Path) -> None:
    """``git checkout HEAD --`` clears index AND worktree, so a staged note was reset
    just as thoroughly. Nothing should stage it, but the guard must not depend on that."""
    _stamp_this_run(repo)
    _git(repo, "add", "--", SESSION_HANDOFF)

    restore_derived_to_head(repo)

    assert THIS_RUN in (repo / SESSION_HANDOFF).read_text(encoding="utf-8")


def test_a_DELETED_handoff_is_still_restored(repo: Path) -> None:
    """The carve-out is about CONTENT, not about the path.

    A deletion has no marker to lose, and letting it ride into the iterate commit would
    drop a tracked file — exactly what the restore exists to prevent. Same rule the F5
    ledger already follows.
    """
    (repo / SESSION_HANDOFF).unlink()

    assert SESSION_HANDOFF in restore_derived_to_head(repo)
    assert (repo / SESSION_HANDOFF).is_file()


def test_a_STAGED_handoff_whose_worktree_copy_is_gone_is_not_restored(repo: Path) -> None:
    """Porcelain ``MD``: modified in the INDEX, deleted from the worktree.

    Both external plan reviewers read the carve-out as "a deleted handoff is never
    restored again" and asked for a new status-sensitive branch. It already exists — the
    run-written branch restores only when the pair is a deletion AND the content is
    confirmed gone — so the answer is coverage, not code. ``MD`` is the shape where the
    marker is still present, in the index: restoring it would blow away exactly what this
    change exists to preserve.
    """
    _stamp_this_run(repo)
    _git(repo, "add", "--", SESSION_HANDOFF)
    (repo / SESSION_HANDOFF).unlink()

    status = _git(repo, "status", "--porcelain", "--", SESSION_HANDOFF).stdout
    assert status.startswith("MD"), f"fixture did not produce an MD state: {status!r}"

    assert SESSION_HANDOFF not in restore_derived_to_head(repo)
    assert THIS_RUN in _git(repo, "show", f":{SESSION_HANDOFF}").stdout


def test_a_handoff_unstaged_with_rm_cached_is_not_restored(repo: Path) -> None:
    """``git rm --cached`` emits a ``D `` line while the file is still ON DISK.

    The status pair alone reads that as a clean deletion, and restoring it would overwrite
    the run's marker — reached by the natural operator move for "get this out of my
    commit". So the pair is necessary but not sufficient: the content must also be gone.
    """
    _stamp_this_run(repo)
    _git(repo, "add", "--", SESSION_HANDOFF)
    _git(repo, "commit", "-m", "seed a handoff commit")
    _git(repo, "rm", "--cached", "-q", "--", SESSION_HANDOFF)

    status = _git(repo, "status", "--porcelain", "--", SESSION_HANDOFF).stdout
    assert status.startswith("D "), f"fixture did not produce a `D ` state: {status!r}"
    assert (repo / SESSION_HANDOFF).is_file(), "the file must still be on disk"

    assert SESSION_HANDOFF not in restore_derived_to_head(repo)
    assert THIS_RUN in (repo / SESSION_HANDOFF).read_text(encoding="utf-8")


def test_the_return_value_never_claims_the_handoff(repo: Path) -> None:
    """It reports what it restored. A caller logging that list must not read the
    opposite of what happened."""
    _stamp_this_run(repo)

    assert SESSION_HANDOFF not in restore_derived_to_head(repo)

