"""Handoff freshness — does ``session_handoff.md`` describe the run being verified.

Two checks live here because they answer one question off one marker:

* :func:`check_session_handoff_fresh` — the F11 iterate-finalization check.
* :func:`check_c3_session_handoff_fresh_after_phase` — the Canon **C3** check the
  phase verifiers and the Stop-hook phase-quality audit run.

The F11 half moved off filesystem mtime in iterate-2026-07-27-name-the-blocker;
C3 followed in iterate-2026-07-27-c3-phase-content-key. They are deliberately
neighbours: keeping the second one in ``common.py`` would have put a second
implementation of "is this handoff fresh" in a second module, which is the drift
``lib.canon_frontmatter`` was extracted to prevent — and these two would have
drifted on *semantics*, not merely on parsing.

**Why mtime had to go.** The old rule was "the file was written in the last 600
seconds". That fires on any run that spends more than ten minutes waiting on CI
— a property of the schedule, not of the artifact — and it contradicted a
decision this repo had already taken and acted on: a former timestamp-drift
detector was deleted in iterate-2026-06-28 because filesystem mtime is not a
content-staleness signal in a git repo (checkout, branch-switch and worktree
creation all reset it; see ``hooks/check_drift.py``). A warning that fires on
structure rather than on defects is one operators learn to ignore, which is
worse than no warning at all.

**What replaced it.** The handoff says which run generated it, in the canon
frontmatter ``lib.canon_frontmatter`` parses — the same marker the Stop hook
already uses to decide whether regenerating would clobber a canon handoff. Both
checks now ask the question they actually care about: does this handoff name
*this* run.

**Why C3 keys on the run and not on the phase.** The obvious key for a
phase-scoped check is the marker's ``phase`` field, and it is wrong.
``verify_phase.py --phase all`` hands ONE ``run_id`` to eight phase dispatchers
(``dispatch_all``), each of which checks C3 against the SAME
``session_handoff.md`` — the handoff is overwritten, never appended. Under a
phase key at most one phase, whichever wrote last, could pass; the other seven
would warn. That is a new structural false fire, the exact defect class this
change removes. C1/C2/C4/C5 can ask per-phase questions because events, the
dashboard, the decision log and the changelog all *accumulate*; C3 reads a
single mutable file, which is what its old docstring meant by "session_handoff
is a single file without per-phase markers".

So C3 keys on the run and *reports* the phase. Known bound, stated rather than
papered over: if phase P skips its C3 step but a later phase Q of the same run
writes the marker, C3 passes for P on Q's write. Per-phase attribution needs a
per-phase artifact; the handoff cannot carry one.

Resolution order for F11, most authoritative first:

1. **canon frontmatter ``run_id``** — records which run generated the file.
2. **the ``- **Run ID**:`` line under ``## Current Iterate Progress``** — the
   fallback for a handoff written before the marker existed, or by a path that
   does not set it.

Both are exact-value comparisons against a NAMED marker, never a substring
search for the run id: a handoff carries a second ``- **Run ID**:`` line under
``## Last Iterate`` naming the PREVIOUS run, so a loose search would accept a
handoff generated by the run before this one.

Severity stays WARNING for both — the handoff is advisory, not load-bearing.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

_SCRIPTS_ROOT = Path(__file__).resolve().parents[2]
if str(_SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_ROOT))

from lib.canon_frontmatter import parse_canon_frontmatter  # noqa: E402

from .common import CheckResult, Severity  # noqa: E402

_NAME = "session_handoff.md fresh"
_C3_NAME = "C3 session_handoff.md fresh"

#: Phases whose finalization writes the canon marker, so C3 has a producer to
#: verify. Seven pipeline phases call ``generate_session_handoff.py
#: --canon-marker --phase <phase>``; ``iterate`` supplies the same block from
#: ``tools/finalize_iterate.py``. ``security`` / ``compliance`` / ``adopt`` write
#: no marker and are skipped BY NAME — the Stop-hook canon runner invokes C3 for
#: every phase in ``PLUGIN_TO_PHASE``, so without this set a content key would
#: turn a schedule-driven false fire into a permanent one. Kept aligned with
#: ``PLUGIN_TO_PHASE`` by ``test_c3_canon_phases_align_with_plugin_to_phase``.
C3_CANON_PHASES: frozenset[str] = frozenset({
    "project", "design", "plan", "build", "test", "changelog", "deploy", "iterate",
})

#: Degenerate run ids — no resolvable run context. Mirrors
#: ``_iterate_run_id._RUN_ID_SENTINELS`` / ``phase_quality.RUN_ID_SENTINELS``;
#: duplicated rather than imported because ``lib.phase_quality.__init__`` imports
#: ``_runners``, which imports THIS module — importing back would close the cycle.
_RUN_ID_SENTINELS: frozenset[str] = frozenset({"", "unknown"})

#: Marker values are host-of-record data but still arbitrary file content; clip
#: before they reach a Stop-hook finding so a malformed handoff cannot dump a
#: wall of text into operator output.
_MAX_MARKER_CHARS = 120

#: C0, DEL and C1 ranges. These details are rendered into terminals and logs
#: (``format_report`` emits real ANSI itself), so an ESC or OSC sequence carried
#: in a tracked handoff — or in a supplied run id — could rewrite what the
#: operator sees. Strip rather than escape: nothing downstream needs the bytes.
_CONTROL_CHARS_RE = re.compile(r"[\x00-\x1f\x7f-\x9f]")

#: The in-flight run's id, as rendered by ``lib.handoff_iterate``. Anchored to the
#: ``## Current Iterate Progress`` section so the ``## Last Iterate`` line (the
#: PREVIOUS run) cannot satisfy the check.
_PROGRESS_SECTION_RE = re.compile(
    r"^##\s+Current Iterate Progress\s*$(?P<body>.*?)(?=^##\s|\Z)",
    re.MULTILINE | re.DOTALL,
)
_RUN_ID_LINE_RE = re.compile(r"^-\s+\*\*Run ID\*\*:\s*(?P<run_id>\S+)\s*$", re.MULTILINE)


def progress_run_id(content: str) -> str:
    """The run id named under ``## Current Iterate Progress``, or ``""``."""
    section = _PROGRESS_SECTION_RE.search(content)
    if not section:
        return ""
    line = _RUN_ID_LINE_RE.search(section.group("body"))
    return line.group("run_id") if line else ""


@dataclass(frozen=True)
class _Handoff:
    """A structured read of the tracked handoff.

    ``problem`` is non-empty exactly when the file could not be read at all;
    ``marker`` is ``None`` when the file was read but carries no canon marker.
    The two are distinct states with distinct operator remedies, which is why
    this returns a record rather than an optional string.
    """

    problem: str = ""
    content: str = ""
    marker: dict[str, str] | None = None


def _read_handoff(project_root: Path) -> _Handoff:
    """Read the tracked handoff and parse its canon marker, without judging it.

    Missing and unreadable are resolved by ATTEMPTING the read, not by
    ``is_file()``: that helper swallows the ``OSError`` from an inaccessible
    path and answers ``False``, which would report a handoff that exists but
    cannot be opened as one that was never written — two different defects with
    two different remedies, collapsed into the wrong one.
    """
    path = Path(project_root) / ".shipwright" / "agent_docs" / "session_handoff.md"
    try:
        content = path.read_text(encoding="utf-8", errors="ignore")
    except FileNotFoundError:
        return _Handoff(problem="session_handoff.md missing")
    except OSError as exc:
        return _Handoff(problem=f"session_handoff.md unreadable ({type(exc).__name__})")
    # `parse_canon_frontmatter` already returns None for absent, malformed, and
    # non-canon (`canon_generated` not true) blocks — one gate, not three.
    return _Handoff(content=content, marker=parse_canon_frontmatter(content))


def _clip(value: str) -> str:
    """Bound and de-fang a value before it enters an operator-facing detail."""
    value = " ".join(_CONTROL_CHARS_RE.sub(" ", str(value)).split())
    return value if len(value) <= _MAX_MARKER_CHARS else value[:_MAX_MARKER_CHARS] + "…"


def _warn(detail: str, name: str = _NAME) -> CheckResult:
    return CheckResult(name, False, detail, severity=Severity.WARNING.value)


def check_session_handoff_fresh(project_root: Path, run_id: str = "") -> CheckResult:
    """Pass iff the handoff names ``run_id`` as the run it belongs to."""
    handoff = _read_handoff(project_root)
    if handoff.problem == "session_handoff.md missing":
        return _warn(handoff.problem)
    if not run_id:
        # Never a silent SKIP: a caller that supplies no run id has turned the
        # check off, and that has to be visible rather than read as a pass.
        return _warn("cannot evaluate: no run id supplied")
    if handoff.problem:
        return _warn(handoff.problem)

    if handoff.marker is not None:
        marked = handoff.marker.get("run_id", "")
        if marked == run_id:
            return CheckResult(_NAME, True, f"canon frontmatter names {_clip(run_id)}")
        return _warn(
            f"handoff was generated by {_clip(marked) or '(no run_id in marker)'}, "
            f"not {_clip(run_id)} — re-run the F5b handoff refresh so it describes this run"
        )

    named = progress_run_id(handoff.content)
    if named == run_id:
        return CheckResult(_NAME, True, f"'Current Iterate Progress' names {_clip(run_id)}")
    return _warn(
        f"no canon frontmatter, and 'Current Iterate Progress' names "
        f"{_clip(named) or '(no run id)'}, not {_clip(run_id)} — re-run the F5b handoff refresh"
    )


def check_c3_session_handoff_fresh_after_phase(
    project_root: Path,
    phase: str,
    *,
    run_id: str,
) -> CheckResult:
    """C3 — the handoff belongs to the run whose ``phase`` is being verified.

    ``run_id`` is keyword-only with NO default on purpose: this check has eight
    call sites, and a default would let a missed one silently compare against
    ``""`` and warn forever. A caller that genuinely has no run context passes an
    empty/sentinel value and gets a stated "cannot evaluate" result instead.

    ``phase`` selects applicability (see :data:`C3_CANON_PHASES`) and is reported
    in the passing detail; it is not the pass/fail key — see the module docstring
    for why a phase key would false-fire under ``--phase all``.
    """
    if phase not in C3_CANON_PHASES:
        return CheckResult(
            _C3_NAME,
            None,
            f"not applicable for phase={phase} (writes no canon-marker handoff)",
            severity=Severity.SKIPPED.value,
        )
    if str(run_id).strip().lower() in _RUN_ID_SENTINELS:
        return _warn("cannot evaluate: no run id supplied", _C3_NAME)

    handoff = _read_handoff(project_root)
    if handoff.problem:
        return _warn(handoff.problem, _C3_NAME)
    if handoff.marker is None:
        return _warn(
            "session_handoff.md has no canon marker — re-run the phase's C3 step "
            "(generate_session_handoff.py --canon-marker --phase "
            f"{phase})",
            _C3_NAME,
        )

    marked = handoff.marker.get("run_id", "")
    if not marked:
        return _warn("canon marker carries no run id", _C3_NAME)
    if marked != run_id:
        return _warn(
            f"handoff was generated by {_clip(marked)}, not {_clip(run_id)} — re-run "
            f"the phase's C3 step so it describes this run",
            _C3_NAME,
        )

    wrote = _clip(handoff.marker.get("phase", "")) or "(unnamed)"
    return CheckResult(
        _C3_NAME, True,
        f"canon marker names {_clip(run_id)} (written at phase {wrote})",
    )


__all__ = [
    "C3_CANON_PHASES",
    "check_c3_session_handoff_fresh_after_phase",
    "check_session_handoff_fresh",
    "progress_run_id",
]
