"""F11 check — ``session_handoff.md`` describes the run that is finishing.

Split out of ``iterate_checks`` in iterate-2026-07-27-name-the-blocker, when the
check stopped keying on filesystem mtime.

**Why mtime had to go.** The old rule was "the file was written in the last 600
seconds". That fires on any run that spends more than ten minutes waiting on CI
— a property of the schedule, not of the artifact — and it contradicted a
decision this repo had already taken and acted on: a former timestamp-drift
detector was deleted in iterate-2026-06-28 because filesystem mtime is not a
content-staleness signal in a git repo (checkout, branch-switch and worktree
creation all reset it; see ``hooks/check_drift.py``). A warning that fires on
structure rather than on defects is one operators learn to ignore, which is
worse than no warning at all.

**What replaced it.** The handoff says which run generated it, in the canon
frontmatter ``lib.canon_frontmatter`` parses — the same marker the Stop hook
already uses to decide whether regenerating would clobber a canon handoff. The
verifier now asks the question it actually cares about: does this handoff name
*this* run.

Resolution order, most authoritative first:

1. **canon frontmatter ``run_id``** — records which run generated the file.
2. **the ``- **Run ID**:`` line under ``## Current Iterate Progress``** — the
   fallback for a handoff written before the marker existed, or by a path that
   does not set it.

Both are exact-value comparisons against a NAMED marker, never a substring
search for the run id: a handoff carries a second ``- **Run ID**:`` line under
``## Last Iterate`` naming the PREVIOUS run, so a loose search would accept a
handoff generated by the run before this one.

Severity stays WARNING — the handoff is advisory, not load-bearing.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_SCRIPTS_ROOT = Path(__file__).resolve().parents[2]
if str(_SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_ROOT))

from lib.canon_frontmatter import parse_canon_frontmatter  # noqa: E402

from .common import CheckResult, Severity  # noqa: E402

_NAME = "session_handoff.md fresh"

#: The in-flight run's id, as rendered by ``lib.handoff_iterate``. Anchored to the
#: ``## Current Iterate Progress`` section so the ``## Last Iterate`` line (the
#: PREVIOUS run) cannot satisfy the check.
_PROGRESS_SECTION_RE = re.compile(
    r"^##\s+Current Iterate Progress\s*$(?P<body>.*?)(?=^##\s|\Z)",
    re.MULTILINE | re.DOTALL,
)
_RUN_ID_LINE_RE = re.compile(r"^-\s+\*\*Run ID\*\*:\s*(?P<run_id>\S+)\s*$", re.MULTILINE)


def progress_run_id(content: str) -> str:
    """The run id named under ``## Current Iterate Progress``, or ``""``."""
    section = _PROGRESS_SECTION_RE.search(content)
    if not section:
        return ""
    line = _RUN_ID_LINE_RE.search(section.group("body"))
    return line.group("run_id") if line else ""


def _warn(detail: str) -> CheckResult:
    return CheckResult(_NAME, False, detail, severity=Severity.WARNING.value)


def check_session_handoff_fresh(project_root: Path, run_id: str = "") -> CheckResult:
    """Pass iff the handoff names ``run_id`` as the run it belongs to."""
    handoff = Path(project_root) / ".shipwright" / "agent_docs" / "session_handoff.md"
    if not handoff.is_file():
        return _warn("session_handoff.md missing")
    if not run_id:
        # Never a silent SKIP: a caller that supplies no run id has turned the
        # check off, and that has to be visible rather than read as a pass.
        return _warn("cannot evaluate: no run id supplied")
    try:
        content = handoff.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return _warn(f"session_handoff.md unreadable ({type(exc).__name__})")

    frontmatter = parse_canon_frontmatter(content)
    if frontmatter is not None:
        marked = frontmatter.get("run_id", "")
        if marked == run_id:
            return CheckResult(_NAME, True, f"canon frontmatter names {run_id}")
        return _warn(
            f"handoff was generated by {marked or '(no run_id in marker)'}, not {run_id} "
            "— re-run the F5b handoff refresh so it describes this run"
        )

    named = progress_run_id(content)
    if named == run_id:
        return CheckResult(_NAME, True, f"'Current Iterate Progress' names {run_id}")
    return _warn(
        f"no canon frontmatter, and 'Current Iterate Progress' names "
        f"{named or '(no run id)'}, not {run_id} — re-run the F5b handoff refresh"
    )


__all__ = ["check_session_handoff_fresh", "progress_run_id"]
